### ISSUE TITLE
deadrxsezzz - TxBuilderExtension.sol doesn't work properly when using ETH

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#100]
deadrxsezzz

medium

# TxBuilderExtension.sol doesn't work properly when using ETH

## Summary
When using TxBuilderExtension.sol user can directly work with native token. However, there is a flaw in the logic. 

## Vulnerability Detail
When repaying/ supplying native token, amount is not passed, but rather msg.value is used. This could cause problems if a user tries to execute `repayNativeToken` and `supplyNativeToken` in the same tx as they both would attempt to pass msg.value as a parameter. If `repayNativeToken` is first called, it will succeed and if there is any excess ETH, it will send it to the user leaving no balance in the contract to execute `supplyNativeToken`
```solidity
function repayNativeToken(address user) internal nonReentrant {
        uint256 repayAmount = msg.value;

        ironBank.accrueInterest(weth);
        uint256 borrowBalance = ironBank.getBorrowBalance(user, weth);
        if (repayAmount > borrowBalance) {
            WethInterface(weth).deposit{value: borrowBalance}();
            IERC20(weth).safeIncreaseAllowance(address(ironBank), borrowBalance);
            ironBank.repay(address(this), user, weth, borrowBalance);
            (bool sent,) = user.call{value: repayAmount - borrowBalance}("");
            require(sent, "failed to send native token");
        } else {
            WethInterface(weth).deposit{value: repayAmount}();
            IERC20(weth).safeIncreaseAllowance(address(ironBank), repayAmount);
            ironBank.repay(address(this), user, weth, repayAmount);
        }
    }
```
if `supplyNativeToken` is first called, it will send the whole `msg.value` and `repayNativeToken` will then fail. 
```solidity
function supplyNativeToken(address user) internal nonReentrant {
        WethInterface(weth).deposit{value: msg.value}();
        IERC20(weth).safeIncreaseAllowance(address(ironBank), msg.value);
        ironBank.supply(address(this), user, weth, msg.value);
    }
```
Furthermore, if there is any excess ETH in the contract for whatever reason, adversary can make use of this and steal it, as they can just call execute with 2 `supplyNativeToken` actions with `msg.value = address(TxBuilderExtension.sol).balance`

## Impact
When using `TxBuilderExtension.sol`, two actions using Native Token cannot be called in the same tx or it will revert.
If there is any excess ETH in the contract, adversary can steal it. 

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L252-#L256
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L290-#L306

## Tool used

Manual Review

## Recommendation
Instead of using `msg.value` as a parameter, let the user specify the amount and pass it as an argument.

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
The issue is different from the marked main #198 
TXBuilderExtension is supposed to work with ETH. The problem I describe is that it always passes msg.value as an argument. If there are 2 operations with eth, as described above, it will revert.
I expect a revaluation.

**Comment by 0xffff11** [comment]
It is the same thing as explained in https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/31 so they are dups. See my comment there and see if you can please answer it thanks

**Comment by hrishibhat** [comment]
This issue can be considered a valid low as the user can always do the same in two separate transactions. 
Don't this a vulnerability or breaking any core functionality causing damage. 
@iamjakethehuman @0xffff11 @ibsunhub

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/31#issuecomment-1636149001

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/100/#issuecomment-1606055751): accepted
