### ISSUE TITLE
Brenzee - Fail to accrue interests on all user's token positions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#109]
Brenzee

high

# Fail to accrue interests on all user's token positions

## Summary
Functions `supply`, `borrow`, `repay`, `redeem` and `liquidate` in `IronBank.sol` execute `_accrueInterest(market)` function to initiate interest accrual for the relevant market, but fail to do so for other markets where the user has entered. As a consequence, this oversight could result in incorrect calculations of the position's debt and potentially misclassify the user's liquidation status when `_checkAccountLiquidity` or `_isLiquidatable` is called.

## Vulnerability Detail
The function `_checkAccountLiquidity` checks whether a user is liquidatable by taking into account the user's all debt markets and supply markets. This function is called at the end of `borrow`, `redeem`, and `liquidate` functions. The issue is that the `_accrueInterest` is called only for one market (two markets for `liquidate` function) which accruals interest only for one market (or 2 in `liquidate`) and ignores all of the other markets where the user has entered, which could lead to incorrectly calculated collateral and incorrectly calculated debt.

This results in two possible scenarios:
- The debt of the user is lower than what it should be (all the debt hasn't been calculated correctly)
- User can be prematurely liquidated (all the collateral hasn't been calculated correctly)

## Impact
Interest is not accrued on all the markets that the user has entered which could lead to debt and collateral not being calculated correctly which could lead the user to have debt lower than it should be or the user is in danger to be liquidated prematurely.

## Code Snippet
`borrow`, `redeem`, and `liquidate` functions accrue interest only for **one market** (two in `liquidate`)
Example in`borrow`
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L361
Example in `liquidate`
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L495-L496

At the end of `borrow`, `redeem` and `liquidate` functions `_checkAccountLiquidity` is called
Example in `borrow`
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L393

`_getAccoundLiquidity` (which is used in `_checkAccountLiquidity`) calculates total collateral and total debt across **all the markets user has entered in**.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1032-L1058

Similar functionality is for function `_isLiquidatable` which checks if the `debtValue` across **all the markets** is greater than `liquidationCollateralValue` 
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1065-L1092

## Tool used
Manual Review

## Recommendation
Need to accrue interest on every market that the user has entered to eliminate the possibility of the user getting prematurely liquidated or the debt being lower than it should be.

**Comment by Brenzee** [comment]
Escalate for 10 USDC
I think this is a valid issue.
For example, if a user enters multiple different markets and interest isn't accrued on all markets where the user has entered, he has a risk of getting liquidated even though the user has enough collateral in the other markets.

**Comment by 0xffff11** [comment]
Duplicate of #499

**Comment by hrishibhat** [comment]
Result:
Low
Unique  
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/499#issuecomment-1639544768

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Brenzee](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/109/#issuecomment-1606058593): rejected
