### ISSUE TITLE
rvierdiiev - IronBank._getAccountLiquidity should acrrue interests for all user's markets in order to receive correct collateral/debt balance

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#11]
rvierdiiev

medium

# IronBank._getAccountLiquidity should acrrue interests for all user's markets in order to receive correct collateral/debt balance

## Summary
IronBank._getAccountLiquidity should acrrue interests fro all user's markets in order to receive correct collateral/debt balance. Because it's not done now, that means that user can be allowed/disallowed to borrow, when he shouldn't/should be able to.
## Vulnerability Detail
`_getAccountLiquidity` function is used by protocol in order to understand how many collateral and debt user has through the all markets.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1032-L1058
```solidity
    function _getAccountLiquidity(address user) internal view returns (uint256, uint256) {
        uint256 collateralValue;
        uint256 debtValue;

        address[] memory userEnteredMarkets = allEnteredMarkets[user];
        for (uint256 i = 0; i < userEnteredMarkets.length; i++) {
            DataTypes.Market storage m = markets[userEnteredMarkets[i]];
            if (!m.config.isListed) {
                continue;
            }

            uint256 supplyBalance = m.userSupplies[user];
            uint256 borrowBalance = _getBorrowBalance(m, user);

            uint256 assetPrice = PriceOracleInterface(priceOracle).getPrice(userEnteredMarkets[i]);
            require(assetPrice > 0, "invalid price");
            uint256 collateralFactor = m.config.collateralFactor;
            if (supplyBalance > 0 && collateralFactor > 0) {
                uint256 exchangeRate = _getExchangeRate(m);
                collateralValue += (supplyBalance * exchangeRate * assetPrice * collateralFactor) / 1e36 / FACTOR_SCALE;
            }
            if (borrowBalance > 0) {
                debtValue += (borrowBalance * assetPrice) / 1e18;
            }
        }
        return (collateralValue, debtValue);
    }
```
As you can see this function doesn't accrue interests for all user's markets. That means that collateral balance and debt balance could be wrong for that markets, because accruing interests has impact on both exchange ratio and borrow index.
## Impact
User's collateral/debt balance is not up to date.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
You need to  accrue interests for all markets of user.

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc. I believe this was wrongly excluded.

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/499#issuecomment-1639544768

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/11/#issuecomment-1606912610): rejected
