### ISSUE TITLE
0xHati - accrueInterest is underestimating interest rate because it doesn't compound

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#116]
0xHati

medium

# accrueInterest is underestimating interest rate because it doesn't compound

## Summary
Interest rate is not calculated optimally because it's possible `accrueInterest` isn't called very frequent. This way the actual interest rate calculated is different than if `accrueInterest` would've been called every block , because the function doesn't use compounding in it's calculation.
## Vulnerability Detail
Accrue interest is called from various functions to update various state variables before doing any other actions such as supplying, borrowing, redeeming and so on. The function calculates the interest by getting the interest rate per second, it multiplies that with the time difference passed between the last call of this method. It's possible the `accrueInterest` hasn't been called frequently, example once a week. However, if this method would have been called every block the interest rate would be bigger because of compounding. It's possible for markets that are less used the time between function calls is greater and thus the actual interest rate will be significantly lower than it should be. 

Please find similar report from OZ of Aave and Compound on the same issue: 
[Aave M-08](https://blog.openzeppelin.com/aave-protocol-audit)
[Compound](https://blog.openzeppelin.com/compound-audit)

## Impact
Discrepancy between the computed and theoretical interest since if `accrueInterest` has not been called in a block or if it would've been called every block the actual interest rate will differ. The difference between the actual interest rate and the theoretical will depend on the time difference between function calls and the actual interest rate itself. If the interest rate itself is higher, the lack of compounding will result in a higher difference.
## Code Snippet
[Link to code](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L906)
```solidity
uint256 interestFactor = borrowRatePerSecond * timeElapsed;
```
## Tool used

Manual Review

## Recommendation
Calculate interest rate using compounding.

**Comment by 0xHati** [comment]
Escalate for 10 usdc. 

I would like to know why this was excluded. It seems to me interest rate calculation is suboptimal for the users, considering this is a lending protocol where interest rate is one of the key aspects it would seem the protocol would like to optimize this so users get the best rate and don't lose out on potential gains. As written in my report this same issue was brought up in other mayor lending protocols such as Aave and Compound.

**Comment by ib-tycho** [comment]
There is a trade-off between gas efficiency and interest optimization. If the goal is to optimize interest, anyone can call accrueInterest() at any time. However, it's important to consider the potential impact on gas costs when making this decision.

If a market has not been frequently interacted with, it indicates that the market is not active, resulting in lower interest to accrue. Conversely, a market with a significantly high interest rate will attract more deposits and thus accrue interest more frequently. This is the normal functioning of the market.

**Comment by ib-tycho** [comment]
We acknowledge this issue and will not fix

**Comment by 0xffff11** [comment]
Agree with escalation and the given resources, also sponsor confirmed. I think it can be a medium

**Comment by 0xffff11** [comment]
According to further discussion: 
'''
There has been a discussion where the sponsor and the lead senior both think it is truly a low due to being a design decision.

Also there is a very similar issue in the past for sherlock that was also marked it as a low: 

https://github.com/sherlock-audit/2023-02-surge-judging/issues/55#issuecomment-1483784885

So I have 3 references that bring me to the low PoV + me thinking it is also a design decision, againts some report from OZ. 

Given that in the past it was judged as a low too and all the opinions involved, I think low is the right category. Thanks 
'''

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on Sponsor comment as this is a design decision

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xHati](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/116/#issuecomment-1606129240): rejected
