### ISSUE TITLE
Ruhum - IronBank allows deposits into markets that are not seizable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#117]
Ruhum

medium

# IronBank allows deposits into markets that are not seizable

## Summary
IronBank allows deposits into markets that are not seizable allowing the user to borrow funds without the risk of being liquidated

## Vulnerability Detail
A position can only be liquidated if the underlying collateral is seizable:
```sol
    function liquidate(
        address liquidator,
        address borrower,
        address marketBorrow,
        address marketCollateral,
        uint256 repayAmount
    ) external nonReentrant isAuthorized(liquidator) {
        // ...
        require(isMarketSeizable(mCollateral), "collateral market cannot be seized");
        // ...
    }

    function isMarketSeizable(DataTypes.Market storage m) internal view returns (bool) {
        return !m.config.isTransferPaused() && m.config.liquidationThreshold > 0;
    }
```

A market is not seizable if the transfer of IBTokens is disabled or the liquidation threshold is 0. But, that doesn't prevent users from supplying more assets to that market to borrow additional funds.

`supply()` only checks whether the supply function is paused:

```sol
    function supply(address from, address to, address market, uint256 amount)
        external
        nonReentrant
        isAuthorized(from)
    {
        DataTypes.Market storage m = markets[market];
        require(m.config.isListed, "not listed");
        require(!m.config.isSupplyPaused(), "supply paused");
        require(!isCreditAccount(to), "cannot supply to credit account");
        // ...
    }
```

## Impact
Since unseizable markets are unfit to be used as collateral (can't be liquidated), you expose the protocol to potentially unhealthy debt.

A user can increase their collateral position to borrow additional funds without risking liquidation.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L313
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L491
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1099

## Tool used

Manual Review

## Recommendation
`supply()` should not allow you to deposit additional funds into a market if it's unseizable.

**Comment by 0xruhum** [comment]
Escalate for 10 USDC

Allowing a user to supply collateral to an unseizable market allows them to borrow funds without the position being liquidatable. That allows bad debt to build up in the system.

**Comment by 0xffff11** [comment]
I see it as a duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/162 the main point is basically the same.  I can see a medium here. Thoughts? @ibsunhub

**Comment by ibsunhub** [comment]
Hmm, transfer pause is a security guard if an emergency happened. Normally, we will pause supply and borrow first. Then we might pause transfer if it's necessary. Therefore, if a market is transfer paused, it should be also supply paused. Not to mention that enforcing transfer pause check on supply function is logically strange.
It's invalid and we won't fix it.

**Comment by hrishibhat** [comment]
@0xruhum do you have any further comments?

**Comment by 0xruhum** [comment]
Pausing supply and transfers are two different functions. The current implementation doesn't guarantee that the supply functionality will be paused when transfers are paused. So I do think the issue is valid.

> Not to mention that enforcing transfer pause check on supply function is logically strange.

Yes, but it's necessary to prevent a user from borrowing funds using collateral that's unseizable. Otherwise, the funds can't be considered collateral.

I can't argue whether the protocol team will always first pause the supply functionality and then pause transfers. In an emergency situation, mistakes can happen. But, a simple check in the `supply()` function will prevent the issue from potentially being abused.

Since this can potentially have an effect on all users, as you allow bad debt to build up, the downside is considerably bigger than the additional gas cost.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Based on the above comments This would be possible only in case of an admin error. 
In addition to the comment here. 
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/117#issuecomment-1623496228

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xruhum](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/117/#issuecomment-1607732956): rejected
