### ISSUE TITLE
rvierdiiev - IronBank._isLiquidatable should acrrue interests for all user's markets in order to receive correct collateral/debt balance

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#12]
rvierdiiev

medium

# IronBank._isLiquidatable should acrrue interests for all user's markets in order to receive correct collateral/debt balance

## Summary
IronBank._isLiquidatable should acrrue interests for all user's markets in order to receive correct collateral/debt balance. Because it's not done now, that means that user can be liquidated when he actually has enough collateral.
## Vulnerability Detail
`_isLiquidatable` function is used by protocol in order to understand if user has enough collateral to cover his debt. To do that function loops through all user's markets.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1065-L1092
```solidity
        function _isLiquidatable(address user) internal view returns (bool) {
        uint256 liquidationCollateralValue;
        uint256 debtValue;

        address[] memory userEnteredMarkets = allEnteredMarkets[user];
        for (uint256 i = 0; i < userEnteredMarkets.length; i++) {
            DataTypes.Market storage m = markets[userEnteredMarkets[i]];
            if (!m.config.isListed) {
                continue;
            }

            uint256 supplyBalance = m.userSupplies[user];
            uint256 borrowBalance = _getBorrowBalance(m, user);

            uint256 assetPrice = PriceOracleInterface(priceOracle).getPrice(userEnteredMarkets[i]);
            require(assetPrice > 0, "invalid price");
            uint256 liquidationThreshold = m.config.liquidationThreshold;
            if (supplyBalance > 0 && liquidationThreshold > 0) {
                uint256 exchangeRate = _getExchangeRate(m);
                liquidationCollateralValue +=
                    (supplyBalance * exchangeRate * assetPrice * liquidationThreshold) / 1e36 / FACTOR_SCALE;
            }
            if (borrowBalance > 0) {
                debtValue += (borrowBalance * assetPrice) / 1e18;
            }
        }
        return debtValue > liquidationCollateralValue;
    }
```
As you can see this function doesn't accrue interests for all user's markets. That means that collateral balance and debt balance could be wrong for that markets, because accruing interests has impact on both exchange ratio and borrow index. 
## Impact
User can be liquidated, when he has enough collateral.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
You need to accrue interests for all markets of user.

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc. I believe this was wrongly excluded.

**Comment by 0xffff11** [comment]
Duplicate of #201 See my comment there. Thanks

**Comment by hrishibhat** [comment]
Result:
Low
Unique 
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/499#issuecomment-1639544768

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/12/#issuecomment-1606912195): rejected
