### ISSUE TITLE
BenRai - Bad actor can create an account that cannot be liquidated

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#144]
BenRai

high

# Bad actor can create an account that cannot be liquidated

## Summary
When checking if an account can be liquidated the function `IronBank._is Liquidatable` is called. It loops over all markets an account has entered and can run out of gas if the account has entered to many markets. This results in an account that can never be liquidated since the check if the account can be liquidated cannot be finished. 

## Vulnerability Detail

When an account deposits into a market or borrowing from a market, the market that was interacted with is added to the array of markets the account has entered ( mapping `allEnteredMarkets`). According to feedback from the Iron Bank team there will not be a maximum amount of market in the Iron Bank. This means that a bad actor can deposit some collateral, borrow the close to the maximum amount of money against the deposited collateral. After that he can interact with a lot of other markets by borrowing 1 wei from each market to increase the length of the `allEnteredMarkets` array. This way the account is save from liquidation. When he wants to redeem the collateral he exits some markets by repaying the borrowed amount and can now repay the big credit and redeem his collateral.    

## Impact
The account can not be liquidated what can lead to bad debt for the Iron Bank

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/IronBank.sol#L1070

## Tool used

Manual Review

## Recommendation
Establishing a maximum number of markets an account can enter can solve this issue

Duplicate of #232

**Comment by BenRai1** [comment]
escalate for 10 USD

Based on the information proided by the team that there will not be a limit on markets for the iron bank this issue should be valid. Would be great to also get a feedback from the project team and to understand the reasening of the judge why this issue should be excluded.

**Comment by 0xffff11** [comment]
Duplicate of #232

**Comment by hrishibhat** [comment]
Result:
Invalid
Duplicate of #232

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BenRai1](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/144/#issuecomment-1606736881): rejected
