### ISSUE TITLE
BenRai - If a user enters to many markets, core functionalities of the Iron Bank do not work anymore.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#146]
BenRai

medium

# If a user enters to many markets, core functionalities of the Iron Bank do not work anymore.

## Summary

When an account uses the function `IronBank.borrow()`, `IronBank.redeem`, `IronBank.deferLiquidityCheck` and `IronBank.transferIBToken` the liquidity of the account is checked to makes sure the interactions are nor exceeding the accounts liquidity and making it liquidatable. If an account interacts with to many markets, the array of markets the account has entered ( mapping `allEnteredMarkets`) becomes very long. Since according to feedback from the Iron Bank team there will not be a limit of markets in the Iron Bank the array can become infinitely long. When checking the liquidity of an account the function `IronBank. _getAccountLiquidity ()` is called. It loops over all entered markets. This function can run out of gas if the array is to long and make the above functions unusable.

## Vulnerability Detail
If borrowing, redeeming, transferring IB tokens and deferring liquidity check are not possible any more this results in a bad user experience. The user will not be able to borrow even if he has enough collateral deposited, he will not be able to redeem his collateral even if the borrowed amount is way less than his collateral is worth and he will not be able to use flash loans or transfer his IB tokens. To fix this issue the account will need to exit some markets meaning that he will need to repay some of the markets he borrowed from. Such inconvenience will lead to the user leaving the Iron Bank. Since this will only happen to big and active accounts the impact of them removing their liquidity will be the biggest for the Iron Bank.    

## Impact
Bad customer experience for big accounts resulting in them leaving the Iron Bank and reducing the banks liquidity and TVL

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/pool/IronBank.sol#L1037-L1056

## Tool used

Manual Review

## Recommendation

Limit the number of markets an account can enter 

Duplicate of #232

**Comment by BenRai1** [comment]
escalate for 10 USD

Based on the information provided by the team that there will not be a limit on markets for the Iron Bank this issue should be valid. Users that have entered a lot of markets will be the once that are very active on the platform and normally interact with the biggest amounts of money. Losing them as customers because their accounts become unusable will lead to significant lose in fees for the Iron Bank. Therefore, in my opinion this issue should be valid.

**Comment by 0xffff11** [comment]
Duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/232

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #232

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [BenRai1](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/146/#issuecomment-1606799067): rejected
