### ISSUE TITLE
rvierdiiev - IronBank.redeem should round up ibToken amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#15]
rvierdiiev

medium

# IronBank.redeem should round up ibToken amount

## Summary
IronBank.redeem doesn't round up ibToken amount that should be removed from user's balance.
## Vulnerability Detail
`IronBank.redeem` function allows user to receive some `amount` of underlying tokens, in exchange of burning its ibToken.
This is how ibToken amount that should be burnt is calculated:
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L421-L427
```solidity
        if (amount == type(uint256).max) {
            ibTokenAmount = userSupply;
            amount = (ibTokenAmount * _getExchangeRate(m)) / 1e18;
            isRedeemFull = true;
        } else {
            ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);
        }
```
In case if amount is not unit256.max, then `(amount * 1e18) / _getExchangeRate(m)` is used to get ibToken amount.
The problem here is that this calculation should round up `ibTokenAmount`.
## Impact
User redeems less amount of ibToken in exchange of `amount` of underlying tokens.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Round up `ibTokenAmount`.
```solidity
        if (amount == type(uint256).max) {
            ibTokenAmount = userSupply;
            amount = (ibTokenAmount * _getExchangeRate(m)) / 1e18;
            isRedeemFull = true;
        } else {
            ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);
            if (ibTokenAmount * _getExchangeRate(m) / 1e18 != amount) ibTokenAmount += 1; 
        }
```

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc. I believe this was wrongly excluded.

**Comment by 0xffff11** [comment]
I see the issue as a low.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low as there is no clear explanation of the impact of the loss if any.
