### ISSUE TITLE
deadrxsezzz - Users may be completely DOS'd due to OUT_OF_GAS attacks

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#156]
deadrxsezzz

high

# Users may be completely DOS'd due to OUT_OF_GAS attacks

## Summary
Out of gas error may occur/ be forced  in `_isLiquidatable` which will lead to a user being completely unable to call any function but `supply()` in IronBank

## Vulnerability Detail
When calling `borrow()`, `redeem()`, `liquidate()` and `transferIBTokens()`, account liquidity is checked and `_isLiquidatable()` is called.
The current way `isLiquidatable()` works is by iterating over `userEnteredMarkets[user]`. 
```solidity
address[] memory userEnteredMarkets = allEnteredMarkets[user];
        for (uint256 i = 0; i < userEnteredMarkets.length; i++) {
            DataTypes.Market storage m = markets[userEnteredMarkets[i]];
            if (!m.config.isListed) {
                continue;
            }

            uint256 supplyBalance = m.userSupplies[user];
            uint256 borrowBalance = _getBorrowBalance(m, user);

            uint256 assetPrice = PriceOracleInterface(priceOracle).getPrice(userEnteredMarkets[i]);
            require(assetPrice > 0, "invalid price");
            uint256 liquidationThreshold = m.config.liquidationThreshold;
            if (supplyBalance > 0 && liquidationThreshold > 0) {
                uint256 exchangeRate = _getExchangeRate(m);
                liquidationCollateralValue +=
                    (supplyBalance * exchangeRate * assetPrice * liquidationThreshold) / 1e36 / FACTOR_SCALE;
            }
            if (borrowBalance > 0) {
                debtValue += (borrowBalance * assetPrice) / 1e18;
            }
        }
``` 
This has multiple issues with it:
1. Lack of limit of markets a user can enter.
2. For every asset, external call to oracle is made, costing a lot of gas 
3. Combined with my other gas griefing issue - adversary can call `supply()` for another user for as low as 1 wei, entering the market for them. After calling any function which calls `isLiquidatable()`, the function will go over the market + call to the oracle, making the function much more costly. Also adversary can force enter a market for another user by sending them 1 wei of IBTokens

## Impact
User completely being unable to use IronBank. 100% loss of user funds. 

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1069-#L1090

## Tool used

Manual Review

## Recommendation
before accessing the storage slot for the market, check if `userEnteredMarkets[i] == address(0)``and continue the for loop if so. 
add access control to who can supply for a user. consider a minValue for supplying
add a limit to markets a user can enter

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC 
The issue above shows a possible scenario where the whole contract may enter a DOS state. Nothing in it will work anymore and all user funds will be stuck/ lost.
I expect a revaluation.

**Comment by 0xffff11** [comment]
Duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/232

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a non-issue based on the discussion in https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/232

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/156/#issuecomment-1606056167): rejected
