### ISSUE TITLE
Auditwolf - Full redemption with outstanding borrow balance.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#158]
Auditwolf

high

# Full redemption with outstanding borrow balance.

## Summary

when redeeming assets , users are not allowed to fully redeem  assets if the have outstanding borrow balance. to ensure this the redeem function checks if it is a full redemption triggered by the user and if the user has zero balance. if both are true the user is allowed to exit the market. In the case that the user has requested a full redemption but has a non zero borrow balance , they will be denied to exit the market but the code continues to fully redeem assets  for  the  user.

## Vulnerability Detail

         if (isRedeemFull && _getBorrowBalance(m, from) == 0) {
            _exitMarket(market, from);
        }

        IBTokenInterface(m.config.ibTokenAddress).burn(from, ibTokenAmount); // Only emits Transfer event.
        IERC20(market).safeTransfer(to, amount);

        _checkAccountLiquidity(from);

As shown users are only  allowed to exit the market if they have zero outstanding borrow balance. This check however does not prevent users from fully redeeming assets if the have a non zero borrow balance. 

NOTE : users who not aware that they can only fully redeem assets if they have zero outstanding borrow balance might assume full redemption can always be performed regardless of their borrow balance. 
## Impact

users assets might get locked in the market leading to loss of usability or liquidity.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L406C2-L452C1

## Tool used

Manual Review

## Recommendation
Add a checking mechanism to prevent users from fully redeeming assets if the have a borrow balance >  0 .

**Comment by htstarz** [comment]
Escalate for 10 usdc
It should not be possible to fully redeem assets if a user has a borrow balance > 0 yet this is possible since The code only checks if there is need to exit market  but does not prevent users from fully redeeming assets with outstanding borrow balance. This might cause users assets to get stuck they try to do so. please confirm with protocol team if not sure whether it should be possible to fully redeem assets with outstanding borrow balance.

**Comment by 0xffff11** [comment]
I do not have it very clear here, I think it is invalid, thoughs? @ibsunhub

**Comment by ibsunhub** [comment]
I'm not quite sure about the question. If a user has a borrow balance on market A, he can still redeem market A supply as long as he has supply balance on other markets and his total collateral value is larger than his total debt value.

**Comment by htstarz** [comment]
Check account liquidity does not guarantee that the total collateral value is larger than the total debt value of a user since liquidity status check might be in a deferred state. Furthermore, its also possible that the user has entered only one market.

**Comment by ibsunhub** [comment]
Yes, the account liquidity check could be deferred. However, this action will mark the variable `liquidityCheckStatus` to be DIRTY. In the end, the account liquidity will be checked eventually.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L529

**Comment by ibsunhub** [comment]
It's possible a user has entered one market. For example, he supplies and borrows the same market. What's the problem?

**Comment by ibsunhub** [comment]
Let me clarify:

1). Entered market means that the user has supply balance or borrow balance.
- If user redeems all but still has borrow balance, the market is still entered.
- If user repays all but still has supply balance, the market is still entered.
- If user has neither supply balance nor borrow balance, the market will be exited.

2). The condition that a user could redeem from a market has nothing to do with the borrow balance he hold. As long as the account liquidity check is passed (total collateral value > total debt value), he could redeem.

3). Defer liquidity check can defer the check but not ignore. If a user defers the liquidity check, after the callback is finished, the protocol will check the account liquidity in the end.

**Comment by hrishibhat** [comment]
@htstarz any further comments?

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on Sponsor comments.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [htstarz](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/158/#issuecomment-1607040024): rejected

**Comment by htstarz** [comment]
run this test and it seems its possible to fully redeem with outstanding borrow balance

function testCannotRedeemforoutstandingborrowbalance()public {
        uint256  supplyAmount = 100e18;
        uint256  redeemAmount = 100e18;
        uint256  borrowbalnce = 30e18;
        
        

        vm.startPrank(user1);
        market1.approve(address(ib), supplyAmount);
        ib.supply(user1, user1, address(market1), supplyAmount);
        
        vm.expectRevert("insufficient collateral");
        ib.redeem(user1, user1, address(market1), type(uint256).max);
     }   
}

**Comment by ibsunhub** [comment]
Can you paste the full test case?

Like I said, as long as the account liquidity check is passed, it's nothing wrong to redeem all his supply balance even the user has borrow balance on the same market. It means the user must have supply balance on other market and the total collateral value must be larger than the total debt value.

**Comment by ibsunhub** [comment]
> run this test and it seems its possible to fully redeem with outstanding borrow balance
> 
> function testCannotRedeemforoutstandingborrowbalance()public { uint256 supplyAmount = 100e18; uint256 redeemAmount = 100e18; uint256 borrowbalnce = 30e18;
> 
> ```
>     vm.startPrank(user1);
>     market1.approve(address(ib), supplyAmount);
>     ib.supply(user1, user1, address(market1), supplyAmount);
>     
>     vm.expectRevert("insufficient collateral");
>     ib.redeem(user1, user1, address(market1), type(uint256).max);
>  }   
> ```
> 
> }

In this snippet, the variable `borrowbalnce` is never used. This user just supply and redeem the same market.
