### ISSUE TITLE
deadrxsezzz - User might spread their collateral across multiple markets in order to make liquidation unprofitable for liquidators

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#172]
deadrxsezzz

medium

# User might spread their collateral across multiple markets in order to make liquidation unprofitable for liquidators

## Summary
User might deposit their collateral in multiple markets in order to make liquidating unprofitable.

## Vulnerability Detail
A user's collateral is calculated by adding up the user's assets in all markets they've entered.  This creates the problem that the user might have their collateral in multiple assets. The liquidator would have to make separate `liquidate()` calls for every different market the borrower has collateral in. Considering `IronBank` plans to be deployed on mainnet, where gas fees are high, this could make liquidations unprofitable for the liquidators.

### Consider the following scenario: 
On mainnet, User A has borrowed $200 and has $240 in collateral assets and is to be liquidated. User A has split their collateral assets equally between 10 markets. In order to be liquidated, the liquidator will have to make separate `liquidate()` calls for every market. Every call will have an ERC20 transfer of the borrowed asset + further calls made within the IronBank contract, including a call to Chainlink oracle. At the time of writing an ERC20 transfer has transaction fees of ~$10-15 ([stETH Example](https://etherscan.io/tx/0x896d6dd35d39f705312f615b35d80bf151a2334ea15725b4de798919f842c361), [USDC Example](https://etherscan.io/tx/0xb0470b33166594b4feccee7aa3d29d884040414c97e56138f6b0e4c60e06c664)). Only the ERC20 transfer fees, excluding the fees for the inner logic within the IronBank contract would be for over $100, making liquidations unprofitable. 

Having properly working liquidation system is important to make sure the project doesn't lose money when borrowers do not repay their loan. If users within liquidation do not get liquidated, project will suffer loss of funds. 

## Impact
Not properly working liquidation system. Users who should be liquidated won't be. Loss of funds for the project.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-#L510

## Tool used

Manual Review

## Recommendation
Add a limit for how many markets could be used as a user's collateral at the same time. Consider adding a min collateral amount on each market in order to make sure transaction fees do not make liquidation unprofitable.
Consider allowing for a liquidator to repay the whole borrower's loan in a single transaction, even if the user's collateral is spread across multiple markets

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
Issue above clearly shows a possible scenario where liquidations will be unprofitable. Liquidations are an important part of the protocol which makes sure the protocol doesn’t lose money. Keeping this issue would cause losses for the protocol.

**Comment by 0xffff11** [comment]
Even though the issue does not speak about a DOS by a user being in a lot of markets. The root cause is the same and the fix too, considering as a duplicate of: https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/232

**Comment by iamjakethehuman** [comment]
The root cause is not the same, as stated in the example, there could be 10 markets (which would not lead to DOS from OOG error) and the liquidations could still be unprofitable due to gas costs. The scenario above describes a possible situation which will lead to unprofitable liquidations/ bad debt for the protocol, recheck it.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on the Sponsor comment on #22 
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/22#issuecomment-1619661167

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/172/#issuecomment-1606057092): accepted
