### ISSUE TITLE
branch_indigo - Liquidation Reverts Due to Insufficient Collateral Balance During Price Drops

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#177]
branch_indigo

high

# Liquidation Reverts Due to Insufficient Collateral Balance During Price Drops

## Summary
In IronBank.sol `liquidate()`, a comparable amount of collateral relative to borrow debts is calculated in `_getLiquidationSeizeAmount()`. Then `_transferIBToken()` is called to transfer the amount of collateral market tokens from borrower to liquidator and reverts when there is insufficient collateral. The reverts make the liquidation process highly vulnerable during a drastic collateral token price drop.
## Vulnerability Detail
During the liquidation process (`liquidate()`), the number of collateral market tokens to be sent to liquidators is based on the `repayAmount` and market `liquidationBonus`. In `_getLiquidationSeizeAmount()`, the amount conversion is done using current price fetched from the oracle. Note that `liquidationBonus` is at least more than 100% based on Constants.sol, which means the liquidator is entitled to an amount of collateral more than the value of the debt they repay.
```solidity
//IronBank.sol
//_getLiquidationSeizeAmount()
        uint256 numerator = (mCollateral.config.liquidationBonus *
            borrowMarketPrice) / FACTOR_SCALE;
        uint256 denominator = (_getExchangeRate(mCollateral) *
            collateralMarketPrice) / 1e18;

        return (repayAmount * numerator) / denominator;
```
Following this, `_transferIBToken` is called to transfer the calculated collateral market token balance amount. This function reverts when there is not enough collateral market token balance in the borrower account. The revert will effectively cause liquidations to revert whenever the calculated collateral market token balance is more than what the borrower has. 
```solidity
//IronBank.sol
//_transferIBToken
    function _transferIBToken(
        address market,
        DataTypes.Market storage m,
        address from,
        address to,
        uint256 amount
    ) internal {
        require(from != address(0), "transfer from the zero address");
        require(to != address(0), "transfer to the zero address");

        uint256 fromBalance = m.userSupplies[from];
        require(amount > 0, "transfer zero amount");
 >>>>       require(fromBalance >= amount, "transfer amount exceeds balance");
```
This might potentially cause mass liquidation reverts in some conditions. For example, when collateral underlying token price drops drastically in a short period of time. This alone likely causes great number of accounts holding the collateral token to be liquidatable. 

Let's say the wstETH collateral value drops to half of the previous price(1000 usd -> 500 usd). At 1000 usd wstETH price, the borrower account maximally borrowed 800 usd Dai against 1000 usd wstETH with an 80% collateral factor ,90% liquidation threshold and 110% liquidation bonus factor. Then wstETH price drops to 500 usd. Now the account holds only 500 usd worth of wstETH against 800 usd Dai in debt. When a liquidator repays 800 usd worth of debt, 880 usd worth of wstETH is required to be transferred from the borrower who only has 500 usd worth of wstETH. This will cause `_transferIBToken` to revert, reverting the liquidation transaction.

It's also should be noted that during incidents of drastic price drops, the trend is likely to continue during on going mass liquidation process. Even though a liquidator is able to reduce the repayment amount, it's still likely the transaction reverts at settlement due to further price drops.

## Impact
The vulnerability likely causes massive liquidation freezes/reverts, when the protocol needs liquidation the most to stay healthy in moments of drastic token value drops, causing the market to be insolvent.  
## Code Snippet
[https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L834-L837](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L834-L837)

[https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L873](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L873)
## Tool used

Manual Review

## Recommendation
keep the existing implementation of `liquidationBonus`. Instead of reverting when there is not enough collateral token balance in `_transferIBToken`, just calculate actual `repayAmount` based on the actual collateral token balance available, and only transfer the actual `repayAmount` to the protocol to `_repay()`.

**Comment by bzpassersby** [comment]
Escalate for [5] USDC
I think this is wrongly excluded. The report describes a valid vulnerability in the liquidation process, which prevents liquidation when the protocol needs liquidation the most during rapid asset price drops.

**Comment by 0xffff11** [comment]
@ibsunhub thoughts on the issue ?

**Comment by ibsunhub** [comment]
This issue is basically the same with #338.

In the above example, if the price of wstETH drops drastically, it would cause bad debt. The liquidator can only seize all of wstETH and repay some DAI. It will leave some un-collateralized DAI borrow. If this case happened, the protocol will cover the bad debt by using the reserves.

To prevent this from happening, we will assess carefully when deciding a market's collateral factor. For example, the collateral factor of a gov token will likely be lower than 50%. In this number, we can handle a 50% price drop. Also, the supply cap and the borrow cap will help mitigate the damage.

Again, this issue is more like a less likely event, not an actual vulnerability. This problem exists on every lending protocol and the protocol will use its reserves to cover bad debt if this happened.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Sponsor comments and consider this a design decision in case of an extreme price drop

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [bzpassersby](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/177/#issuecomment-1608062152): rejected
