### ISSUE TITLE
sashik_eth - Functions associated with steth and wsteth would not work on L2s

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#206]
sashik_eth

medium

# Functions associated with steth and wsteth would not work on L2s

## Summary

Functions associated with `steth` and `wsteth` would not work on L2s.

## Vulnerability Detail

Protocol uses addresses of `steth` and `wsteth` tokens hardcoded after deployment in its `PriceOracle.sol`, `UniswapExtension.sol`, `TxBuilderExtension.sol`. While `wsteth` token exist on all 3 expected chains (mainnet, Arbitrum, Optimism), its functionality is different on L2s, particularity it does not have functions that oracle and other contracts expected to use, for example, `getWstETHByStETH`:
https://arbiscan.io/token/0x5979D7b546E38E414F7E9822514be443A4800529#code

At the same time, `steth` token is not presented on L2s at all.
Since contracts still would be deployed with some appropriate addresses (zero addresses probably) - this would lead to DOS or unexpected behavior of mentioned functionality.

## Impact

All functionality associated with steth and wsteth (oracle and extensions) would not work on L2s.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/oracle/PriceOracle.sol#L32-L33
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L139-L140
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L85-L86

## Tool used

Manual Review

## Recommendation

Consider updating functionality connected with steth and wseth for contracts that would be deployed on L2s.

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
Protocol is expected to be deployed on L2s, while the `wsteth` there works differently than on L1, and `steth` isn't presented at all meaning protocol would not work correctly.

**Comment by 0xffff11** [comment]
Sponsor comment: 
```
Regarding the mistake in the contest details mentioned in the README, we apologize for any confusion caused. When we stated that we would deploy on Arbitrum and Optimism, we meant that we would make the necessary modifications before deployment. This is our standard practice of maintaining contracts with different branches, same as what we did in v1: https://github.com/ibdotxyz/compound-protocol/branches

We are aware of the absence of a registry on OP and Arb, as pointed out by some individuals. We would like to inquire if it is possible to offer the minimum reward for an oracle issue on L2. Thank you.
```
Unfortunately, it is invalid due to a miss-understanding from the docs

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Lead watson comment below on this too being an additional functionality. Impact is low. 
> No need to wrap or upwrap wstETH on L2. This is just excess functionality that wouldn't be purposed on L2. I don't see it as broken, it's just excess functionality. For the oracle, L2 specifically have wstETH oracles https://data.chain.link/optimism/mainnet/crypto-usd/wsteth-usd meaning that it can be used like a normal collateral so that extra functionality isn't needed. Again it's a case of excess functionality that's not needed on L2 so it's not broken.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/206/#issuecomment-1606095309): rejected
