### ISSUE TITLE
sashik_eth - Uni v2 functions of Uniswap extension would not work on L2s

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#207]
sashik_eth

medium

# Uni v2 functions of Uniswap extension would not work on L2s

## Summary

Uni v2 functions of Uniswap extension would not work on L2s.

## Vulnerability Detail

`UniswapExtension.sol` extension is expected to work with Uniswap v2 and v3 AMM. While v3 instances exist on all expected chains (mainnet, Arbitrum, Optimism), v2 is presented only on mainnet:
https://docs.uniswap.org/contracts/v2/reference/smart-contracts/factory

Since contracts still would be deployed with some appropriate addresses (zero addresses probably) - this would lead to DOS or unexpected behavior of mentioned functionality.

## Impact

Uni v2 functions of Uniswap extension would not work on L2s.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L137

## Tool used

Manual Review

## Recommendation

Consider adding checks for Uni v2 functions that the factory address is not zero and revert with the appropriate error in another case.

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
Protocol is expected to be deployed on L2s, while the Uni v2 isn't presented there meaning protocol would not work correctly.

**Comment by 0xffff11** [comment]
Sponsor comment: 
```
Regarding the mistake in the contest details mentioned in the README, we apologize for any confusion caused. When we stated that we would deploy on Arbitrum and Optimism, we meant that we would make the necessary modifications before deployment. This is our standard practice of maintaining contracts with different branches, same as what we did in v1: https://github.com/ibdotxyz/compound-protocol/branches

We are aware of the absence of a registry on OP and Arb, as pointed out by some individuals. We would like to inquire if it is possible to offer the minimum reward for an oracle issue on L2. Thank you.
```
Unfortunately, it is invalid due to a miss-understanding from the docs

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Uni V2 is not needed in L2 and there is no functionality broken. There is no bug here. 
Considering this issue a low issue

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/207/#issuecomment-1606094658): rejected
