### ISSUE TITLE
rvierdiiev - MarketConfigurator.hardDelistMarket function should accrueInterests

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#21]
rvierdiiev

medium

# MarketConfigurator.hardDelistMarket function should accrueInterests

## Summary
`MarketConfigurator.hardDelistMarket` function should accrueInterests, before the `ironBank.delistMarket` call.
## Vulnerability Detail
`MarketConfigurator.hardDelistMarket` function will be called in order to close market. That means that the market is not will be working anymore and anyone can't call supply/redeem/repay functions.

From discord channel:
>The delistMarket function will be called after the market has been paused and the collateral factor has been set to zero by the governance. The Iron Bank team will assess the impact on the remaining suppliers of the market when the collateral factor is set to zero. If the total borrow amount is relatively low, we will cover all debts using our protocol reserves.

So protocol is going to cover all debts by protocol reserves. But in order to have correct debt amount, `accrueInterest` should be called. And it can be called only, when [market is active](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L286).

But `MarketConfigurator.hardDelistMarket` function doesn't accrue interests before `ironBank.delistMarket` call and `ironBank.delistMarket` doesn't call `accrueInterests` as well.
## Impact
Incorrect debt value will be saved.
## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L286
## Tool used

Manual Review

## Recommendation
Call `accrueInterests` in `MarketConfigurator.hardDelistMarket` function.

**Comment by 0xffff11** [comment]
Duplicate of: #499

**Comment by ibsunhub** [comment]
This issue is invalid.

If the market is about to be hard delisted, it's unnecessary to accrue the interests anymore. The market is going to be deprecated / deleted.

**Comment by 0xffff11** [comment]
After sponsors explanation, I agree with invalid and correct the wrong duplication to 499. Invalid

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue based on sponsor comments
