### ISSUE TITLE
R-Nemes - Oracle will return the wrong price if the aggregator hits minAnswer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#214]
R-Nemes

medium

# Oracle will return the wrong price if the aggregator hits minAnswer

# Oracle will return the wrong price if the aggregator hits minAnswer
## Impact
It is important to note that the Chainlink Price Oracle data feed aggregator incorporates two variables, namely minAnswer and maxAnswer values. These variables serve as bounds that prevent the aggregator from updating the latestAnswer value if it falls outside the agreed range of acceptable values.

However, it is crucial to understand that the contract application is still capable of reading the most recent answer from the Chainlink Price Oracle, regardless of whether it falls within the accepted range or not. This implies that the contract's borrowing functionality may utilize asset prices that fall outside the expected range, potentially leading to inaccurate calculations and incorrect borrowing decisions.

The impact of this situation can be significant. Borrowers relying on asset prices that deviate from the acceptable range may face increased risks and potential financial losses. It is crucial to carefully evaluate the implications of using data that falls outside the predefined bounds and consider implementing additional checks or alternative data sources to ensure the accuracy and reliability of asset pricing information.

##  Vulnerability Detail
[chainlink docs]()
*The data feed aggregator includes both minAnswer and maxAnswer values. These variables prevent the aggregator from updating the latestAnswer outside the agreed range of acceptable values, but they do not stop your application from reading the most recent answer.*

[protocol/oracle/PriceOracle.sol#L66-L72](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/oracle/PriceOracle.sol#L66-L72)
```solidity
    function getPriceFromChainlink(address base, address quote) internal view returns (uint256) {
        (, int256 price,,,) = registry.latestRoundData(base, quote);
        require(price > 0, "invalid price");

        // Extend the decimals to 1e18.
        return uint256(price) * 10 ** (18 - uint256(registry.decimals(base, quote)));
    }
```

## Tools Used
Manual review

## Recommendation
`getPriceFromChainlink` function should check the returned price is within some specied bounds and revert if the price is outside those values.

```solidity
    function getPriceFromChainlink(address base, address quote) internal view returns (uint256) {
        (, int256 price,,,) = registry.latestRoundData(base, quote);
        require(price > 0, "invalid price");
		
	if (price >= maxPrice or price <= minPrice) revert();

        // Extend the decimals to 1e18.
        return uint256(price) * 10 ** (18 - uint256(registry.decimals(base, quote)));
    }
```

Duplicate of #25

**Comment by Jonsey** [comment]
The duplicate #25 has been escalated and marked as resolved.  This should also be updated
