### ISSUE TITLE
rvierdiiev - Liquidators can be not interested in liquidation of small debts

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#22]
rvierdiiev

medium

# Liquidators can be not interested in liquidation of small debts

## Summary
Liquidators can be not interested in liquidation of small debts. So this debts will remain in the protocol and will create bad debt.
## Vulnerability Detail
In order to liquidate debt position, IronBank has `liquidate` function. This function allows liquidator to provide amount he wants to liquidate on behalf of debtor.

This will be only done, when liquidation is attractive to liquidator, which means that he will earn smth from the call.
IronBank [uses `liquidationBonus`](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L834) to incentivize liquidators.

But in case if the debt is too small(for example 5$), that means that it can be not attractive for the liquidator to `liquidate` debt, because he will spend more funds as gas payment than he will earn. That means that such debts usually will not liquidated and will remain in the system and create bad debt.

What is worse, is that some liquidators can liquidate accounts not fully, but leave some small amount, exactly to create bad debt, that will not be liquidated by anyone else.

I believe that this is high severity issue, because borrowers, interested repayers and liquidators can make system insolvent, which will cause stakers to redeem.
## Impact
System will face bad debt, which can cause insolvency
## Code Snippet
[Provided](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-L510)
## Tool used

Manual Review

## Recommendation
I guess that you should provide some limits. One of them is to disallow to borrow small amount(minimum limit should be reached). Another is to disallow repayment that again leaves small debt(still should be bigger than limit or repaid fully). And sam ething for the liquidation, small debt can't be leaved.
Using this approach, your debts will always be attractive for liquidators.

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc. I believe this was wrongly excluded.

**Comment by ib-tycho** [comment]
As mentioned by @0xfff11, this is a design decision. The primary objective of market reserves for each market is to cover these minor debts. Ensuring the stability of the protocol is our responsibility, and we regularly monitor and repay these debts using reserves. On the other hand, It is not in the liquidator's interest to leave behind small debts after liquidation, as their goal is to maximize their profits. We don't think it's necessary to set minimum limit for borrow/repay. Thanks.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Sponsor comment and considering this as a design decision. This issue can be considered a low.
