### ISSUE TITLE
dirk_y - User can prevent liquidations if enough markets exist

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#232]
dirk_y

medium

# User can prevent liquidations if enough markets exist

## Summary
If Ironbank were to grow to the same extent as a protocol like Balancer, then there could be enough markets for a user to be able to have an unhealthy borrow position without the risk of being liquidated.

## Vulnerability Detail
A liquidator is likely to follow the following steps before/while performing a liquidation:

1. Calls `isUserLiquidatable` to see if an account is liquidatable
2. Calls `calculateLiquidationOpportunity` to calculate the size of the opportunity
3. Calls `liquidate` with the desired amount of asset to repay

In both of these above calls, the `_isLiquidatable` internal method is called. Importantly, this method loops through all the user entered markets. Thus, a malicious actor could join an arbitrary number of markets to gas grief liquidators (particularly relevant on Ethereum) or with enough markets the malicious actor could even cause any liquidation attempts to revert.

Furthermore, the malicious actor doesn't even need to commit capital to these markets. Not only is there no lower limit to amount in the `supply` method, but an attacker can redeem all their capital with `redeem` without exiting the market. As shown in the snippets below, this is possible because `isRedeemFull` is only true if `amount == type(uint256).max`. The malicious actor could therefore specify the exact amount of their position to withdraw all their capital without exiting the market.

```solidity
        bool isRedeemFull;
        if (amount == type(uint256).max) {
            ibTokenAmount = userSupply;
            amount = (ibTokenAmount * _getExchangeRate(m)) / 1e18;
            isRedeemFull = true;
        }
```

```solidity
        if (isRedeemFull && _getBorrowBalance(m, from) == 0) {
            _exitMarket(market, from);
        }
```

Therefore, for example, a malicious actor could have "positions" in 100 markets, where every position has a supply of 0. They could then borrow against a market with a collateral token that has an unusually high price. As the value of their collateral decreases, the borrow/user becomes liquidatable. 

With sufficient markets, the malicious actor could listen for any `liquidate` calls in the mempool and frontrun these transactions to join another market. This would cause `_isLiquidatable` to iterate over so many markets that the liquidator transaction runs out of gas or reaches the block gas limit.

I spent a lot of time debating whether or not this is a low or medium severity issue but decided it was medium because there is no hard-stop from preventing this situation from occurring. It feels like one of those things that could sit in the background for years before appearing and causing reputational damage. Furthermore, the contest README suggests the number of markets could grow indefinitely to support any "vanilla ERC20s".

## Impact
Malicious actor can borrow against unhealthy collateral and prevent anyone from liquidating their position.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1065
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L420-L424
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L441-L443

## Tool used
Manual Review

## Recommendation
Firstly, the `_exitMarket` condition check in `redeem` should use the same logic as `_repay` by checking for `m.userSupplies[to] == 0` rather than using the `isRedeemFull` variable. This will prevent the malicious attacker from having 0 value market positions.

Secondly, I would suggest a cap on the number of markets that a user can enter. You could add the following line to the `_enterMarket` method:

```solidity
require(allEnteredMarkets[user].length < MAX_MARKET_LENGTH, "too many markets");
```

where `MAX_MARKET_LENGTH` is a sensible constant of your choosing.

**Comment by 0xffff11** [comment]
At the current stage, if there is really no limit on the market number that a user can join, even though the chances are low and user should spend a lot of gas joining every market, if could get to the DOS state, if the market array is long enough. The problem is we don't know how many markets will the user need to join to DOS. Might never reach that point. I could see both low and medium, but tending more to a low

**Comment by 0xffff11** [comment]
If sponsor really thinks this is a reasonable state to reach, it should be a medium

**Comment by ibsunhub** [comment]
Not a reasonable state to reach.

There are many issues related to DOS for too many markets. I ran some tests to check the gas used for multiple markets in function `checkAccountLiquidity`.

- 10 markets: ~370k
- 100 markets: ~3.5m
- 500 markets: ~17.5m

I know there are different aspects could effect the testing results such as more complex ERC20 token logic. The testing result still give us an approximation about the gas consumption. We aim to support at most 20~30 markets in one system. Therefore, it's not reasonable to reach DOS state.

**Comment by 0xffff11** [comment]
Great @ibsunhub  This is the exact info I needed to know. As stated in my previous comment, I wanted to know how many markets were actually needed to reach this state, as it seemed possible, but I wanted to know the exact number. If I am not wrong eth has a 30M block gas limit. According to your results, this won't be reach on the lifetime of the protocol, not even get close to it. If the calculations are correct, I think it should be a low. If the calculations are wrong please do comment on the issue again. Also, it would be helpful if you pasted the code that lead you to this consclusion @ibsunhub

**Comment by djb15** [comment]
I've just checked these numbers and they seem to be in the right ballpark. With the 30M block gas limit this isn't a reachable state. Apologies, I should have validated the gas usage earlier. Agree this should be "low" at best.

**Comment by 0xffff11** [comment]
Hi @djb15 Thanks for confirming, the issue was indeed wall thought, just not reachable at this state. Issue should be low/invalid according to the tests from sponsor and ratification of the tests by watson

**Comment by ibsunhub** [comment]
```
contract AccountLiquidity2Test is Test, Common {
    uint8 internal constant underlyingDecimals = 18; // 1e18
    uint16 internal constant reserveFactor = 1000; // 10%
    uint16 internal constant collateralFactor = 8000; // 80%
    int256 internal constant marketPrice = 1500e8;

    uint256 internal constant numOfMarkets = 100; // TODO: change this

    IronBank ib;
    MarketConfigurator configurator;
    CreditLimitManager creditLimitManager;
    FeedRegistry registry;
    PriceOracle oracle;

    address admin = address(64);
    address user = address(128);

    function setUp() public {
        ib = createIronBank(admin);

        configurator = createMarketConfigurator(admin, ib);

        vm.prank(admin);
        ib.setMarketConfigurator(address(configurator));

        creditLimitManager = createCreditLimitManager(admin, ib);

        vm.prank(admin);
        ib.setCreditLimitManager(address(creditLimitManager));

        TripleSlopeRateModel irm = createDefaultIRM();

        registry = createRegistry();
        oracle = createPriceOracle(admin, address(registry));

        vm.prank(admin);
        ib.setPriceOracle(address(oracle));

        for (uint256 i = 0; i < numOfMarkets; i++) {
            (ERC20Market market,,) =
                createAndListERC20Market(underlyingDecimals, admin, ib, configurator, irm, reserveFactor);

            configureMarketAsCollateral(admin, configurator, address(market), collateralFactor);
            setPriceForMarket(oracle, registry, admin, address(market), address(market), Denominations.USD, marketPrice);

            uint256 amount = 100 * (10 ** underlyingDecimals);
            deal(address(market), user, amount);

            vm.startPrank(user);
            market.approve(address(ib), amount);
            ib.supply(user, user, address(market), amount);
            vm.stopPrank();
        }
    }

    function testCheckAccountLiquidity() public {
        assertEq(ib.getUserEnteredMarkets(user).length, numOfMarkets);

        uint256 checkpointGasLeft1 = gasleft();

        ib.checkAccountLiquidity(user);

        uint256 checkpointGasLeft2 = gasleft();

        uint256 gasDelta = checkpointGasLeft1 - checkpointGasLeft2;
        console.log(gasDelta);
    }
}
```

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comments
