### ISSUE TITLE
tsvetanovv - `liquidationBonus` with a minimum value of `MIN_LIQUIDATION_BONUS` will always revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#24]
tsvetanovv

medium

# `liquidationBonus` with a minimum value of `MIN_LIQUIDATION_BONUS` will always revert

## Summary

`liquidationBonus` with a minimum value of 100% will always revert

## Vulnerability Detail

In `MarketConfigurator.sol` we have `configureMarketAsCollateral` and `adjustMarketLiquidationBonus()` functions.  The first function allows the owner to configure a market as collateral and the second is to adjust the liquidation bonus of a market.
The problem here is that both functions will revert when the minimum allowed value is set. 
The minimum allowed value is in `Constants.sol`:

```solidity
12: uint16 internal constant MIN_LIQUIDATION_BONUS = 10000; // 100%
```
Both Functions have the following check:

```solidity
require(
            liquidationBonus > MIN_LIQUIDATION_BONUS && liquidationBonus <= MAX_LIQUIDATION_BONUS,  
            "invalid liquidation bonus"
        );
```
Оmitted is to add the sign greater than or equal to.

As you can see the function will not allow to set the `liquidationBonus` value to 100% (that is 10000).

## Impact

It is impossible to settle a liquidation bonus of 100%

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/MarketConfigurator.sol#L141
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/MarketConfigurator.sol#L238
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/Constants.sol#L12

## Tool used

Manual Review

## Recommendation

Change:
```solidity
liquidationBonus > MIN_LIQUIDATION_BONUS && liquidationBonus <= MAX_LIQUIDATION_BONUS
```

To:
```solidity
liquidationBonus >= MIN_LIQUIDATION_BONUS && liquidationBonus <= MAX_LIQUIDATION_BONUS
```

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

As I have written this edge case is Valid

**Comment by 0xffff11** [comment]
I struggle to see how much of an edge-case this actually is. @ibsunhub you might understand it better. Imo it is a low, but it depends on the actual impact of it

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low-issue based on sponsor comments. There is no medium impact here
