### ISSUE TITLE
Bauchibred - Lack of Implementation of Fallback Oracles Could Cause Protocol-wide Failure if the Chainlink Oracle Goes Down or Reverts Calls

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#252]
Bauchibred

medium

# Lack of Implementation of Fallback Oracles Could Cause Protocol-wide Failure if the Chainlink Oracle Goes Down or Reverts Calls

## Summary

The dependency on a single oracle, particularly Chainlink, without fallback options presents a significant risk to the PriceOracle protocol. In some extreme cases, oracles can be taken offline or token prices can fall to zero. In these cases, liquidations, deposits and withdrawals or any execution that deals with querying of prices will be frozen (all calls will revert), If the Chainlink oracle for a particular asset is suspended, or the Chainlink multisigs decide to revert the call, all price queries will be inaccessible, potentially causing protocol-wide failure.

## Vulnerability Detail

The PriceOracle contract relies heavily on Chainlink's oracle via the FeedRegistryInterface for pricing data. The contract fetches the asset prices in USD from Chainlink and normalizes the price by the asset's decimals. The contract also employs the Chainlink registry to fetch the latest round data for the specified base and quote assets.

In a case where the Chainlink oracle for a particular asset goes down, or the Chainlink multisigs decide to revert calls, all price queries for that asset will fail. This is because the getPrice and getPriceFromChainlink functions require the price returned from Chainlink's oracle to be greater than zero, or they revert.

```solidity
function getPriceFromChainlink(address base, address quote) internal view returns (uint256) {
    (, int256 price,,,) = registry.latestRoundData(base, quote);
    require(price > 0, "invalid price");

    // Extend the decimals to 1e18.
    return uint256(price) * 10 ** (18 - uint256(registry.decimals(base, quote)));
}
```

The absence of any fallback oracles in the protocol exacerbates this issue. If the Chainlink oracle fails or reverts calls, there are no secondary oracles in place that the protocol can default to. Consequently, this could cause all calls to query the price to be inaccessible, leading to a protocol-wide failure.

## Impact

The protocol's heavy reliance on Chainlink's oracle without a fallback oracle in place presents a significant risk. Should the Chainlink oracle go down or its calls be reverted, the protocol's core functionality could be severely disrupted, potentially leading to a complete system failure (in term of price queries). This could have serious implications for users and the protocol's overall stability and trustworthiness.

## Code Snippet

[PriceOracle.sol#L60-L72](https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/protocol/oracle/PriceOracle.sol#L60-L72)

## Tool used

Manual Review

## Recommendations

Though this introduces a little more complexity, consider implementing fallback oracles to supplement the primary Chainlink oracle. Then also implement all chainlink price queries in try/catch block, if the priary call reverts for any reason, the protocol can fall back on these secondary oracles, thereby ensuring continuous and uninterrupted price data.

Duplicate of #433

**Comment by Bauchibred** [comment]
Escalate for 10USDC

This issue seems to have been missed, but it is a valid duplicate of #433

**Comment by 0xffff11** [comment]
Yes, it is a duplicate of #433 , I agree

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #433
