### ISSUE TITLE
shaka - Market accounting can be broken after delisting and listing it again

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#259]
shaka

high

# Market accounting can be broken after delisting and listing it again

## Summary

Market accounting can be broken after delisting and listing it again.

## Vulnerability Detail

When the market configurator delists a market the market struct is deleted from the `markets` mapping. However, the mappings in the struct [are not cleared](https://docs.soliditylang.org/en/v0.8.20/security-considerations.html#clearing-mappings).

This means that if the market is listed again, the market struct will contain the old values in the `userBorrows` and `userSupplies` mappings, while `totalCash`, `totalBorrow` and `totalSupply` will be zero.

## Impact

The market accounting will be broken, which can lead to many potential issues. One example might be the following case:
- Alice has a borrow balance of 10 USDC and the market is delisted.
- The market is listed again and Alice repays the 5 USDC.
- In the  `_repay` internal function the calculation for the `totalBorrow` amount will underflow, which will result in the amount `type(uint256).max - 5e6`.
```solidity
988    unchecked {
989        newUserBorrowBalance = borrowBalance - amount;
990        // Underflow not possible: amount <= userBorrow <= totalBorrow
991        newTotalBorrow = m.totalBorrow - amount;
992    }
```
- Alice supplies 1 USDC, which not will be overvalued, as the [exchange rate](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L810) will be:
```solidity
((m.totalCash + m.totalBorrow) * 1e18) / totalSupplyPlusReserves = (1e6 + (type(uint256).max - 5e6)) * 1e18 / 1e6;
```
- Bob supplies 1000 USDC, but does not receive ibTokens, as the calculation will round to zero:
```solidity
323     uint256 ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);
```

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L603

## Tool used

Manual review

## Recommendation

A possible solution is that instead of deleting the market struct, the market configurator should set the `isListed` flag to false.

**Comment by shaka0x** [comment]
Escalate for 10 USDC

I think this is a valid issue as:

1) There is no mention either in the documentation of in the code of the scenario of relisting a market not being expected. Using the `delete` keyword instead of setting `isListed` to false shows the intention of resetting all the market data, and this issue shows how it fails to do so.

2) In the scenario of this happening, the consequences for the protocol could be critical.

**Comment by 0xffff11** [comment]
Low . Duplicate of: https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/473

**Comment by ibsunhub** [comment]
fix: https://github.com/ibdotxyz/ib-v2/pull/49

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on sponsor comment
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/426#issuecomment-1620755589

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [shaka0x](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/259/#issuecomment-1606201345): rejected

**Comment by IAm0x52** [comment]
Fix looks good. Adds isDelisted to the config struct preventing delisted markets from being relisted
