### ISSUE TITLE
shaka - Users can get immediately liquidated if market liquidation threshold is decreased

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#260]
shaka

medium

# Users can get immediately liquidated if market liquidation threshold is decreased

## Summary

Users can get immediately liquidated if market liquidation threshold is decreased.

## Vulnerability Detail

The `MarketConfigurator` contract allows the owner to change the liquidation threshold of a market. If the liquidation threshold is decreased for a market that has open positions, some users may get immediately liquidated without time to react.

## Impact

Users can get liquidated without time to react.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/MarketConfigurator.sol#L205-L226

## Tool used

Manual review

## Recommendation

Some possible solutions:
- Use a time lock in case of liquidation threshold decrease for a market that has open positions.
- Keep track of the original liquidation threshold and use it for open positions, so that the change will only affect new positions.

**Comment by shaka0x** [comment]
Escalate for 10 USD

The issue describes a more than likely scenario. There is no way of guaranteeing that users will not get immediately liquidated after a change in the liquidation threshold, which should not be acceptable for the users. Even if the protocol team uses off-chain data to keep track of all open positions and decides not to apply the change if it will affect some users, there can be new transactions submitted in the same block where the change of the liquidation threshold is submitted, that can change the current state of the position.

**Comment by 0xffff11** [comment]
I agree with med. Duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/303

**Comment by 0xffff11** [comment]
I stand corrected on the above statement. The issue requires an admin mistake, therefore falls into the low category because they are trusted.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Admin is trusted for setting these values. Considering this issue a valid low
