### ISSUE TITLE
tsvetanovv - An attacker can apply grieving attack by preventing users from interacting with `repay` function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#30]
tsvetanovv

medium

# An attacker can apply grieving attack by preventing users from interacting with `repay` function

## Summary
In `IronBank.sol` we have [`_repay()`](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L975-L1010)function. This function repays an amount of assets to Iron Bank.
```soldiity
function _repay(DataTypes.Market storage m, address from, address to, address market, uint256 amount)
        internal
        returns (uint256)
    {
        uint256 borrowBalance = _getBorrowBalance(m, to);
        if (amount == type(uint256).max) {
            amount = borrowBalance;
        }

        require(amount <= borrowBalance, "repay too much"); 

        uint256 newUserBorrowBalance;
        uint256 newTotalBorrow;
        unchecked {
            newUserBorrowBalance = borrowBalance - amount;
            // Underflow not possible: amount <= userBorrow <= totalBorrow
            newTotalBorrow = m.totalBorrow - amount;
        }

        // Update storage.
        m.userBorrows[to].borrowBalance = newUserBorrowBalance;
        m.userBorrows[to].borrowIndex = m.borrowIndex;
        m.totalCash += amount;
        m.totalBorrow = newTotalBorrow;

        // Check if need to exit the market.
        if (m.userSupplies[to] == 0 && newUserBorrowBalance == 0) {
            _exitMarket(market, to);
        }

        IERC20(market).safeTransferFrom(from, address(this), amount);

        emit Repay(market, from, to, amount, newUserBorrowBalance, newTotalBorrow);

        return amount;
    }
```
The function is internal and is called in [repay()](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L460C5-L470) and [liquidate()](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-L510).

## Vulnerability Detail
The problem here is whenever a user is going to use `_repay()` function, malicious user (for example Bob) can apply a grieving attack by preventing users from interacting with it. 
Bob could prevent the user from paying her debt fully by just repaying a very small amount of the user's debt in advance and as a result honest user transaction not pass.
```solidity
984: require(amount <= borrowBalance, "repay too much");
```
For example:
- Alice wants to use repay function with full `borrowBalance` 100 tokens and pass `amount=100`.
- Bob observes mempols and do font-run grieving attack with 1 wei.
- Alice the transaction could not go through because of require check:
- `require(amount <= borrowBalance, "repay too much")`

Bob can apply this attack for all other users who are going to repay their debt fully.

## Impact

A malicious user can prevent an honest user from using a key function.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L975-L1010
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L460C5-L470
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-L510

## Tool used

Manual Review

## Recommendation

Instead of this check:
```solidity
        if (amount == type(uint256).max) {
            amount = borrowBalance;
        }
```

Change it like this:
```solidity
        if (amount > borrowBalance) {
            amount = borrowBalance;
        }
```

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

I'm sure this grieving attack is valid

**Comment by 0xffff11** [comment]
I think the same that: https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/157  See my comment there. I would classify it as a low due to the cost to perform the griefs and the no real impact to the user in comparison to the cost of causing them.

**Comment by cvetanovv** [comment]
This is a valid issue and is different from #157 
A user can only use 1 wei to do the attack. This attack has absolutely always been recognized as a Medium in Sherlock.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue as the user can just use `type(uint256).max` to repay their entire remaining balance.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cvetanovv](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/30/#issuecomment-1606703629): rejected
