### ISSUE TITLE
rvierdiiev - TxBuilderExtension.supplyNativeToken uses msg.value

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#31]
rvierdiiev

medium

# TxBuilderExtension.supplyNativeToken uses msg.value

## Summary
TxBuilderExtension.supplyNativeToken and repayNativeToken uses msg.value. In case if both of them are used at some set of transactions, then call will revert.
## Vulnerability Detail
`TxBuilderExtension.supplyNativeToken` function sends all `msg.value` to the weth contract and then supplies it to the IronBank. Also `msg.value`  is used inside `repayNativeToken` function. In case if both of them are used at some set of transactions, then call will revert.
## Impact
Actions set with native token supply and repay will revert.
## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L252-L256
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L291
## Tool used

Manual Review

## Recommendation
Use value provided by user for supply and repay native token calls.

**Comment by rvierdiyev** [comment]
Escalate for 10 usdc. I believe this was wrongly excluded.

**Comment by 0xffff11** [comment]
Can you please give a case were both are used in the same transaction? Thanks!

**Comment by iamjakethehuman** [comment]
User A has borrow in WETH. User A has significantly more ETH than their borrow and wants to repay it + supply the rest of their ETH to IronBank to accrue interest in time.
If the user calls `TxBuilderExtension.sol#execute` with both actions in the same transaction (which would also be beneficial since if he even puts `ACTION_DEFER_LIQUIDITY_CHECK` he'd be able to save gas) , both operations will attempt to send out `msg.value` making the tx revert.

**Comment by hrishibhat** [comment]
This issue can be considered a valid low as the user can always do the same in two separate transactions. 
Don't this this a vulnerability or breaking any core functionality causing damage. 
@iamjakethehuman @0xffff11 @ibsunhub

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low because of the above comment

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/31/#issuecomment-1608873446): rejected

**Comment by ibsunhub** [comment]
> This issue can be considered a valid low as the user can always do the same in two separate transactions. Don't this this a vulnerability or breaking any core functionality causing damage. @iamjakethehuman @0xffff11 @ibsunhub

There are many issues related to the usage of `msg.value` in TxBuilderExtension.sol. The root causes are the same, and the fix is [here](https://github.com/ibdotxyz/ib-v2/pull/53).
