### ISSUE TITLE
tsvetanovv - `redeemNativeToken()` missing to call `accrueInterest` before set `redeemAmount`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#34]
tsvetanovv

high

# `redeemNativeToken()` missing to call `accrueInterest` before set `redeemAmount`

## Summary
In `TxBuilderExtension.sol` we have [`redeemNativeToken()`](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L275-L283) function:
```solidity
    function redeemNativeToken(address user, uint256 redeemAmount) internal nonReentrant {
        if (redeemAmount == type(uint256).max) {
            redeemAmount = ironBank.getSupplyBalance(user, weth);
        }
        ironBank.redeem(user, address(this), weth, redeemAmount);
        WethInterface(weth).withdraw(redeemAmount);
        (bool sent,) = user.call{value: redeemAmount}("");
        require(sent, "failed to send native token");
    }
```
This function redeems the wrapped native token and unwraps it to the user.

## Vulnerability Detail

The problem here if `redeemAmount == type(uint256).max` the function should call 
```solidity
ironBank.accrueInterest(weth)
```

in order to calculate `redeemAmount` correctly.

And then call:
```solidity
277: redeemAmount = ironBank.getSupplyBalance(user, weth);
```

By conditionally calling `accrueInterest` when `redeemAmount` is maximum, the function guarantees that the redemption amount accurately reflects the current supply balance, including any accrued interest.

You can see how you did it in `redeemStEth` and `redeemPToken`:
```solidity
        if (amount == type(uint256).max) {
            ironBank.accrueInterest(pToken);
            amount = ironBank.getSupplyBalance(user, pToken);
        }
```
## Impact

Possible loss of funds due to the wrong `redeemAmount`

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L275-L283

## Tool used

Manual Review

## Recommendation

To ensure the redemption amount reflects the most up-to-date accrued interest, it is generally advisable to include an `accrueInterest` step before retrieving the supply balance. This allows for an accurate calculation of the user's current supply balance, considering any interest that has accumulated.

```solidity
        if (redeemAmount == type(uint256).max) {
	        ironBank.accrueInterest(weth);
            redeemAmount = ironBank.getSupplyBalance(user, weth);
        }
```

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

Lack of accrued interest in this case

**Comment by 0xffff11** [comment]
Duplicate of #499

**Comment by hrishibhat** [comment]
Result:
Low
Unique
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/499#issuecomment-1639544768

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cvetanovv](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/34/#issuecomment-1606701289): rejected
