### ISSUE TITLE
kutugu - AccrueInterest should be called first to get the latest user balance

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#341]
kutugu

medium

# AccrueInterest should be called first to get the latest user balance

## Summary

AccrueInterest should be called first to get the latest user balance. However, in some cases, this is not implemented correctly.  

## Vulnerability Detail

```solidity
        uint256 wstEthAmount;
        if (stEthAmount == type(uint256).max) {
            // @audit When the user enters the maximum value, ironBank automatically calculates the latest user balance for further action
            ironBank.accrueInterest(wsteth);
            wstEthAmount = ironBank.getSupplyBalance(user, wsteth);
        } else {
            wstEthAmount = WstEthInterface(wsteth).getWstETHByStETH(stEthAmount);
        }


        if (redeemAmount == type(uint256).max) {
            // @audit However, accrueInterest is not invoked in some cases.   
            redeemAmount = ironBank.getSupplyBalance(user, weth);
        }
```

## Impact

The balance obtained is not up to date and does not contain Interest. As a result, users cannot perform perfect redeem and repay actions, and some funds remain or some debt remains.    

## Code Snippet

- https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L277

## Tool used

Manual Review

## Recommendation

Call accrueInterest first to get the latest user balance

Duplicate of #499

**Comment by KuTuGu** [comment]
Escalate for 10 USDC
In low activity markets, there is a lot of accrueInterest to be extracted, but not invoking accrueInterest results in fund being remained

**Comment by 0xffff11** [comment]
I see that accrueInterest is not called in also other functions, not just on redeem native: https://github.com/sherlock-audit/2023-05-ironbank/blob/9ebf1702b2163b55479624794ab7999392367d2a/ib-v2/src/extensions/TxBuilderExtension.sol#L275 

I believe this should be a medium, depending on the reasoning for why this is not done in those specific functions

**Comment by 0xffff11** [comment]
Duplicate of #499

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #499 
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/499#issuecomment-1639544768

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kutugu](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/341/#issuecomment-1608669054): rejected
