### ISSUE TITLE
Auditwolf - Excess funds after a swap are not returned to the user.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#405]
Auditwolf

high

# Excess funds after a swap are not returned to the user.

## Summary
If the _amountin_  after a swap is less than the specified _maxswapinamount_  it is required that these excess funds be returned to the user. 

## Vulnerability Detail
     Univ3
        require(amountIn <= maxSwapInAmount, "swap in amount exceeds max swap in amount");
        uniV3AmountInCached = DEFAULT_AMOUNT_CACHED;
    }
        Univ2

        require(amountIn <= maxSwapInAmount, "swap in amount exceeds max swap in amount");
        uniV2AmountInCached = DEFAULT_AMOUNT_CACHED;
    }

As we can we see it is required that the _amountin_ ( actual amount spent ) is less than or equal to the _maxswapinamount_ specified by a user . if  _amountin_ < _maxswapinamount_ , the excess ( i.e maxswapinamount  -  amountin ) should be returned back to the user or else it will result in a loss of value to the user. This has not been considered here.

## Impact
It will result in loss of value to users.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L492C1-L549C1

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/UniswapExtension.sol#L610C5-L658C1
## Tool used

Manual Review

## Recommendation
check the difference between _amountin_ and maxswapinamount and refund it to the _msg.sender_.

**Comment by htstarz** [comment]
Escalate for 10 usdc
It is required that unused funds after a swap refunded to the user.
![Screenshot 2023-06-26 at 05-18-23 Single Swaps Uniswap](https://github.com/sherlock-audit/2023-05-ironbank-judging/assets/124651852/c858d233-d3cb-4b22-b972-1d8a9ab1576f)

**Comment by ibsunhub** [comment]
The reason why Uniswap router refunds the excessive funds to users is that it pulls `amountInMaximum` of funds.

```
// Transfer the specified amount of DAI to this contract.
TransferHelper.safeTransferFrom(DAI, msg.sender, address(this), amountInMaximum);
```

However, it's not the case in UniswapExtension.sol since we don't pull `maxSwapInAmount` of `swapInAsset` in the first place.

**Comment by 0xffff11** [comment]
@ibsunhub you are confirming that the issue exists on the UniswapExtension contract? If so, I see the medium here.

**Comment by ibsunhub** [comment]
No, I was explaining that we don't need to refund users since we don't pull `amountInMaximum` of funds from users in the first place.

**Comment by 0xffff11** [comment]
I agree. But if I am not wrong if you are passing amountIn, uniswap v3 does make their own calculations and does not always take amountIn, sometimes they take less and that amount is not refunded. 

@htstarz is there more context or specific part of the code where this is actually happening. Went through the link in the issue, but it is a bit unclear

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on sponsor comments

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [htstarz](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/405/#issuecomment-1607067557): rejected
