### ISSUE TITLE
tsvetanovv - Every time need to `accrueInterest()` when `repay`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#41]
tsvetanovv

high

# Every time need to `accrueInterest()` when `repay`

## Summary
In `TxBuilderExtension.sol`, functions that use repay tokens to Iron Bank only call `accrueInterest()` under certain circumstances, and this should not be the case. 

## Vulnerability Detail
In `TxBuilderExtension.sol` we have the following function which repays or redems specific token to Iron Bank:
- [repayStEth()](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L356-L368)
- [redeemStEth()](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L338-L349)
- [redeemPToken()](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L390-L399)

We can see that `accrueInterest` is called only when `amount` is the maximum value.

```solidity
if (stEthAmount == type(uint256).max) {
         ironBank.accrueInterest(wsteth);
   .....
   }
```

 `accrueInterest()` should be called regardless of the `amount` to give more accurate data.

## Impact

Possible loss of funds due to not accurate token amount

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L356-L368
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L338-L349
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/extensions/TxBuilderExtension.sol#L390-L399

## Tool used

Manual Review

## Recommendation

To ensure the redemption amount reflects the most up-to-date accrued interest `ironBank.accrueInterest` should be outside the if statement. This allows for an accurate calculation of the user's current supply balance, considering any interest that has accumulated.

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

I think is valid case

**Comment by 0xffff11** [comment]
Duplicate of #499

**Comment by ibsunhub** [comment]
No, this issue is invalid.

The core function `redeem` and `repay` in IronBank.sol will accrue the interests. If you specify the amount you want to repay, there's no need to accrue interests again in the extension. Only if you need to repay in full, you need to get the actual borrow balance in the extension first.

**Comment by 0xffff11** [comment]
After sponsors explanation, I agree with invalid and correct the wrong duplication to 499

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue based on Sponsor comment
