### ISSUE TITLE
tsvetanovv - It is possible for a user to completely redeem an amount of asset from Iron Bank, but not leave the market

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#45]
tsvetanovv

high

# It is possible for a user to completely redeem an amount of asset from Iron Bank, but not leave the market

## Summary
It is possible for a user to completely Redeem an amount of asset from Iron Bank, but not leave the market. This situation is happening in [redeem()](https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L406-L451) function:

```solidity
function redeem(address from, address to, address market, uint256 amount)
        external
        nonReentrant
        isAuthorized(from)
    {
        DataTypes.Market storage m = markets[market];
        require(m.config.isListed, "not listed");

        _accrueInterest(market, m);

        uint256 userSupply = m.userSupplies[from];
        uint256 totalCash = m.totalCash;
  
        uint256 ibTokenAmount;
        bool isRedeemFull;
        if (amount == type(uint256).max) {  
            ibTokenAmount = userSupply;
            amount = (ibTokenAmount * _getExchangeRate(m)) / 1e18;
            isRedeemFull = true;
        } else {
            ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);
        }
  
        require(userSupply >= ibTokenAmount, "insufficient balance");
        require(totalCash >= amount, "insufficient cash");
  
        // Update storage.
        unchecked {
            m.userSupplies[from] = userSupply - ibTokenAmount;
            m.totalCash = totalCash - amount;
            // Underflow not possible: ibTokenAmount <= userSupply <= totalSupply.
            m.totalSupply -= ibTokenAmount;
        }
  
        // Check if need to exit the market.
        if (isRedeemFull && _getBorrowBalance(m, from) == 0) {
            _exitMarket(market, from);
        }  

        IBTokenInterface(m.config.ibTokenAddress).burn(from, ibTokenAmount); // Only emits Transfer event.
        IERC20(market).safeTransfer(to, amount);

        _checkAccountLiquidity(from);

        emit Redeem(market, from, to, amount, ibTokenAmount);
    }
```

## Vulnerability Detail

Consider the following situation:
- Alice wants to redeem a full amount of an asset from the Iron Bank and exit the market. 
- To redeem the full amount she needs to put 100 amount of tokens.
- After Alice does this we go to the following code:
```solidity
420:        bool isRedeemFull;
421:        if (amount == type(uint256).max) {  
422:            ibTokenAmount = userSupply;
423:            amount = (ibTokenAmount * _getExchangeRate(m)) / 1e18;
424:            isRedeemFull = true;
425:        } else {
426:            ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);
427:        }
```
- Alice actually buys all her tokens (100) and wants to get out of the market, but doesn't actually enter the `if` statement.
- The condition `amount == type(uint256).max` checks whether the `amount` parameter is equal to `type(uint256).max`, which is the maximum value representable by a `uint256` variable, and Alice enters the `if` statement.
- Because she does not enter into the `if` statement, `isRedeemFull` is never set to `true` and stays `false`.
- Then we go to the following code in which Alice should exit the market but actually does not pass the check because isRedeemFull remains `false`
```solidity
440:        // Check if need to exit the market.
441:        if (isRedeemFull && _getBorrowBalance(m, from) == 0) {
442:            _exitMarket(market, from);
443:        }
```
## Impact

If the user not entering the `_exitMarket()` function means that the user's account will still be considered as having an open position in the market. The outstanding borrow balance will remain, and the user will continue to accrue interest on their borrowings.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L406-L451

## Tool used

Manual Review

## Recommendation

In the `if` statement, check how many tokens a user can have, not the maximum number. like this `if` statement is executed and when a user wants to redeem everything `isRedeemFull` will be set to true.

**Comment by cvetanovv** [comment]
Escalate for 10 USDC

I think is possible user to redeem a full amount and not enter `_exitMarket`

**Comment by ibsunhub** [comment]
dup to #66 

Acknowledge to this issue, but the severity is pretty low. Not exiting the market won't cause any issue.

**Comment by ibsunhub** [comment]
No fund will be lost.

Entered market means that the user has supply balance **or** borrow balance. If a user has 100 supply balance and he redeems 100 (not redeem type(uint256).max), he still redeems all of his funds. The only issue here is that the protocol still thinks the user has supply balance or borrow balance on this market. It's not a problem.

If the user has borrow balance, the market shouldn't be exited.

**Comment by cvetanovv** [comment]
Yeah, but then he can't use `_enterMarket()` and enter the market because `enteredMarkets[user][market]` is never set to false: https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L937C5-L940C20

Not to mention how many other problems can occur in the future if the protocol thinks that users have never exited the market.

**Comment by ibsunhub** [comment]
He doesn't need to enter the market again since the market was not exited. It won't revert or have any side effect if you try to enter an entered market.

I'm not sure what are the many other problems? The concept of "entered markets" is to save gas when calculating the account liquidity. In this way, we don't need to iterate all the supported markets, just the markets where a user has supply or borrow. If a market is not entered properly, yes it's very critical. But, if a market is not exited properly, it's really not a big deal.

We acknowledge that there is a logic flaw in the `isRedeemFull` check, but we maintain our position that the severity is low.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
As mentioned by the Sponsor not exiting the market has low impact. There is not valid loss of funds or damage to the protocol here.
