### ISSUE TITLE
mrpathfindr - Users should be able to exit the market from the redeem function if userSupply == ibTokenAmount but amount < type(uint256).max

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#66]
mrpathfindr

medium

# Users should be able to exit the market from the redeem function if userSupply == ibTokenAmount but amount < type(uint256).max

## Summary

The `redeem()` function allows a user to withdraw their tokens from the protocol. If the user inputs an amount of `type(uint256).max)`  which will set ` isRedeemFull = true` allowing the user to exist the market. But this is not the case for amount < type(uint256).max)`. Users should still be able to exit in this case. 

## Vulnerability Detail

The `redeem()` function allows a user to withdraw their tokens from the protocol. If the user inputs an amount of `type(uint256).max)` then ` isRedeemFull = true` because ` ibTokenAmount = userSupply;`  and the user is able to exit the market. However if the user inputs an amount < `type(uint256).max)` then they may still be in the market ...but this calculation ` `ibTokenAmount = (amount * 1e18) / _getExchangeRate(m); ` can equate to ` ibTokenAmount = userSupply`  which should therefore allow the user to exit the market. 

This code snippet checks the input amount from the user

```solidity
        uint256 ibTokenAmount;
        bool isRedeemFull;
        if (amount == type(uint256).max) {
            ibTokenAmount = userSupply;
            amount = (ibTokenAmount * _getExchangeRate(m)) / 1e18;
            isRedeemFull = true;
        } else {
            ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);
        }

```

It is possible for the result of    `ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);`  to be equal to  `ibTokenAmount = userSupply` as is the case when `amount == type(uint256).max`

The function does not check if this is true, as such  `isRedeemFull` will not be set to `true` and the user will not be exited from the market here:

```solidity
      // Check if need to exit the market.
        if (isRedeemFull && _getBorrowBalance(m, from) == 0) {
            _exitMarket(market, from);
        }
```

## Impact

User will not be appropriately existed from the market if they do not input an amount `amount == type(uint256).max`

## Code Snippet

https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L406-L451

## Tool used

Manual Review

## Recommendation

Check if `ibTokenAmount = userSupply` after this calculation `ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);` in `redeem` so the user can exit the market in the case where amount < type(uint256).max

```solidity

   if (amount == type(uint256).max) {
            ibTokenAmount = userSupply;
            amount = (ibTokenAmount * _getExchangeRate(m)) / 1e18;
            isRedeemFull = true;
        } else {
            ibTokenAmount = (amount * 1e18) / _getExchangeRate(m);    
              if(ibTokenAmount = userSupply){
                 isRedeemFull = true;
              }
        }
```
This will allow the user to therefor exit the market. As is the appropriate behaviour when ibTokenAmount = userSupply

**Comment by mrpathfindr** [comment]
Escalate for 10 USDC 

This issue should be a valid medium. There is an obvious logical error (which was confirmed by the sponsor in conversation). In the scenario where the users input amount is not type(uint256).max but `ibTokenAmount = userSupply`     `isRedeemFull` will remain false. Which is incorrect.... 

As I have shown, the function should check if `ibTokenAmount = userSupply` in the else condition.


Impact is also clearly stated, the user account will not be exited from the market in this scenario.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
As mentioned by the Sponsor in #45  not exiting the market has low impact. There is no valid loss of funds or damage to the protocol here.

**Comment by ibsunhub** [comment]
fix: https://github.com/ibdotxyz/ib-v2/pull/51

**Comment by IAm0x52** [comment]
Fix looks good. _exitMarket is now triggered if user redeems entire balance but doesn't use type(uint256).max
