### ISSUE TITLE
deadrxsezzz - Allowing for the oracle to get an asset's price based off another asset's data feed possesses a risk

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#91]
deadrxsezzz

medium

# Allowing for the oracle to get an asset's price based off another asset's data feed possesses a risk

## Summary
When setting an asset's Chainlink aggregator, said asset can be linked to a different base/quote pair.

## Vulnerability Detail
Allowing for an asset to be linked to a different base/quote pair  opens up unnecessary risks for the protocol. I suppose the idea is for 1:1 assets (e.g. stETH and ETH) to be able to use each other's data feeds in case one goes down/ doesn't exist. However, linking two assets in such ways opens up numerous attack vectors as depegs happen.

An example : 
stETH is linked to ETH's Chainlink Data Feeds. stETH depegs and goes down in value. People can now buy it cheaply, deposit it in IronBank and use it with an inflated value, taking what really are undercollateralized loans, draining money from the project. 

## Impact
In case an asset is linked to another asset's data feeds and one depegs, IronBank will be drained.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/oracle/PriceOracle.sol#L97-#L116

## Tool used

Manual Review

## Recommendation
Do not link any asset to another asset's data feeds.

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
Allowing for an oracle to get an asset's price based of another asset is an unnecessary risk and a vulnerability. I believe this to be a valid finding

**Comment by 0xffff11** [comment]
It is unclear to me that this is something that currently happens in the code or the sponsor has the ability to do. 
@ibsunhub can you confirm?

**Comment by ibsunhub** [comment]
Umm... we did need to be careful when setting the price feed in the oracle. However, it's an admin function. I think it's not a valid issue.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/oracle/PriceOracle.sol#L97

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low based on Sponsor comments, since this is an admin function.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/91/#issuecomment-1608990816): rejected
