### ISSUE TITLE
deadrxsezzz - Liquidating doesn't check `m.config.isTransferPaused()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#93]
deadrxsezzz

medium

# Liquidating doesn't check `m.config.isTransferPaused()`

## Summary
Markets have the option to pause transfers in certain scenarios. However, liquidating doesn't check if market is paused.

## Vulnerability Detail
When liquidating, there lacks a check of whether the market transfer is paused. This would allow for liquidations/ transfers in cases where users shouldn't really be able to. 
Contrary, when normally transferring IBTokens, via `transferIBToken()` there is a check if transfer is paused. When transferring same IBTokens via `liquidate()` there isn't a check. 
```solidity
function liquidate(
        address liquidator,
        address borrower,
        address marketBorrow,
        address marketCollateral,
        uint256 repayAmount
    ) external nonReentrant isAuthorized(liquidator) {
        DataTypes.Market storage mBorrow = markets[marketBorrow];
        DataTypes.Market storage mCollateral = markets[marketCollateral];
        require(mBorrow.config.isListed, "borrow market not listed");
        require(mCollateral.config.isListed, "collateral market not listed");
        require(isMarketSeizable(mCollateral), "collateral market cannot be seized");
        require(!isCreditAccount(borrower), "cannot liquidate credit account");
        require(liquidator != borrower, "cannot self liquidate");

        _accrueInterest(marketBorrow, mBorrow);
        _accrueInterest(marketCollateral, mCollateral);

        // Check if the borrower is actually liquidatable.
        require(_isLiquidatable(borrower), "borrower not liquidatable");

        // Repay the debt.
        repayAmount = _repay(mBorrow, liquidator, borrower, marketBorrow, repayAmount);

        // Seize the collateral.
        uint256 ibTokenAmount = _getLiquidationSeizeAmount(marketBorrow, marketCollateral, mCollateral, repayAmount);
        _transferIBToken(marketCollateral, mCollateral, borrower, liquidator, ibTokenAmount);
        IBTokenInterface(mCollateral.config.ibTokenAddress).seize(borrower, liquidator, ibTokenAmount); // Only emits Transfer event.

        emit Liquidate(liquidator, borrower, marketBorrow, marketCollateral, repayAmount, ibTokenAmount);
    }
```

## Impact
Liquidating people in cases where liquidations shouldn't be possible. Transferring tokens when market is supposed to be paused.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L564
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-#L510

## Tool used

Manual Review

## Recommendation
When liquidating, check if transfer is paused for said market.

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
The issue points out possible transfers of IBtokens when market is supposedly paused. Basically not properly functioning pausing mechanism. I believe it to be valid Medium

**Comment by iamjakethehuman** [comment]
Furthermore, this could be used for normal transfers by two users. Consider the following scenario:
1. User A has IBTokens in a market where transfer is paused. User A wants to send these tokens to User B. 
2. User A takes out a loan against these IBTokens.
3. User A lets some time go by so the loan goes into liquidation.
4. User A sends the borrowed tokens to user B
5. User B uses the borrowed tokens to liquidate User A's loan and receives the IBTokens. 
Although the transfer was supposedly paused, User A successfully managed to transfer tokens to User B. (Although there were some extra fees this way.)

**Comment by ibsunhub** [comment]
We did check.
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L491
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L1100

**Comment by 0xffff11** [comment]
Sponsor showed that this is being checked. Invalid

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Non-issue based on the above comments.
