### ISSUE TITLE
deadrxsezzz - Credit accounts are able to receive IBTokens when they shouldn't be able to

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#94]
deadrxsezzz

medium

# Credit accounts are able to receive IBTokens when they shouldn't be able to

## Summary
Credit accounts can receive IBTokens via liquidating, even though they shouldn't be able to. 

## Vulnerability Detail
Based on the #L566 we can see that credit accounts are not supposed to receive IBTokens
```solidity
function transferIBToken(address market, address from, address to, uint256 amount) external {
        DataTypes.Market storage m = markets[market];
        require(m.config.isListed, "not listed");
        require(msg.sender == m.config.ibTokenAddress, "!authorized");
        require(!m.config.isTransferPaused(), "transfer paused");
        require(from != to, "cannot self transfer");
        require(!isCreditAccount(to), "cannot transfer to credit account");

        _accrueInterest(market, m);
        _transferIBToken(market, m, from, to, amount);

        _checkAccountLiquidity(from);
    }
```
```solidity
require(!isCreditAccount(to), "cannot transfer to credit account");
```
However, when liquidating, such check that the liquidator isn't a credit account doesn't exist. This would allow for credit accounts to liquidate and receive IBTokens, even though they are not supposed to. 
```solidity
function liquidate(
        address liquidator,
        address borrower,
        address marketBorrow,
        address marketCollateral,
        uint256 repayAmount
    ) external nonReentrant isAuthorized(liquidator) {
        DataTypes.Market storage mBorrow = markets[marketBorrow];
        DataTypes.Market storage mCollateral = markets[marketCollateral];
        require(mBorrow.config.isListed, "borrow market not listed");
        require(mCollateral.config.isListed, "collateral market not listed");
        require(isMarketSeizable(mCollateral), "collateral market cannot be seized");
        require(!isCreditAccount(borrower), "cannot liquidate credit account");
        require(liquidator != borrower, "cannot self liquidate");

        _accrueInterest(marketBorrow, mBorrow);
        _accrueInterest(marketCollateral, mCollateral);

        // Check if the borrower is actually liquidatable.
        require(_isLiquidatable(borrower), "borrower not liquidatable");

        // Repay the debt.
        repayAmount = _repay(mBorrow, liquidator, borrower, marketBorrow, repayAmount);

        // Seize the collateral.
        uint256 ibTokenAmount = _getLiquidationSeizeAmount(marketBorrow, marketCollateral, mCollateral, repayAmount);
        _transferIBToken(marketCollateral, mCollateral, borrower, liquidator, ibTokenAmount);
        IBTokenInterface(mCollateral.config.ibTokenAddress).seize(borrower, liquidator, ibTokenAmount); // Only emits Transfer event.

        emit Liquidate(liquidator, borrower, marketBorrow, marketCollateral, repayAmount, ibTokenAmount);
    }
```

## Impact
Credit accounts will receive IBTokens even though they are not supposed to.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-#L510
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L566

## Tool used

Manual Review

## Recommendation
Check if liquidator is Credit account or allow for credit accounts to receive IBTokens even through `transferIBToken()`

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
At numerous instances there are restrictions that credit account cannot receive IBTokens. Such check is missing in ‘liquidate’ method, when in reality it should be there.

**Comment by 0xffff11** [comment]
I think it is low but not sure. What do you think @ibsunhub

**Comment by ibsunhub** [comment]
Low, dup to #98 #304 #458

**Comment by hrishibhat** [comment]
Result:
Low
Unique
https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/98#issuecomment-1639594847

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/94/#issuecomment-1606054049): rejected
