### ISSUE TITLE
deadrxsezzz - A user can front-run becoming a credit account and take a unliquidateable loan.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#96]
deadrxsezzz

high

# A user can front-run becoming a credit account and take a unliquidateable loan.

## Summary
A user can front-run becoming a credit account and take a loan which can then not be liquidated as the user is a creditAccount. 

## Vulnerability Detail
Suppose a user is about to become a credit account and be given a small credit limit on market A. User front-runs the `setCreditLimit` tx and takes a large borrow in market B against some collateral they have. Now that they are a credit account they cannot get liquidated for this large borrow. Furthermore, the user can even use his credit limit on market A and take even more unliquidateable borrow. 
The user can then treat the first borrow as an option - since he cannot get liquidated for it, he can wait as long as they want and at any time get whichever between the collateral and the borrow costs more. 

## Impact
A user can take a large unliquidateable loan

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L351-#L397
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-#L510

## Tool used

Manual Review

## Recommendation
Either change the CreditAccount status to be directly linked to a certain market, or do not allow users to become Credit accounts if they have outstanding debts.

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC 
The issue describes a possible scenario where the user can take out a large loan and prevent liquidation. Should be revaluated imo

**Comment by 0xffff11** [comment]
@ibsunhub  I do not think this is a duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/255 , neither seems valid to me. What do you think?

**Comment by ibsunhub** [comment]
Invalid.

How can people front-run `setCreditLimit`? It's an admin function.

**Comment by ibsunhub** [comment]
I think they are different issues but both are invalid to me.

**Comment by iamjakethehuman** [comment]
@ibsunhub this would be the way to execute the plan step-by-step.
1. User A expects to get credit limit on Market X
2. Admin calls `setCreditLimit` giving some credit limit to user A on market X (so far, tx only goes in the mempool, doesn't execute just yet)
3. User A sees the tx in the mempool and front-runs it to take a large borrow on market Y
4. `setCreditLimit` executes and gives user A the credit limit on market X
5. The user now spends their credit limit on market X 
---------
In the end - the user has a borrow equal to his credit limit on market X (as he was supposed to) + has a large borrow on market Y which cannot be liquidated

**Comment by ibsunhub** [comment]
How can he take a large borrow on market Y since he only has credit limit on market X? Not to mention the transaction is still in the mempool, how can he front-run it to borrow market X? (I assume the account has no collateral.)

Also, credit accounts are seen as trusted party.

**Comment by iamjakethehuman** [comment]
As stated in the original issue, the borrow on market Y is against some collateral.
The borrow on market Y is backed up by collateral which cannot be liquidated. This opens up the problem as if the collateral's value goes down, user cannot be liquidated and IronBank suffers losses.

**Comment by ibsunhub** [comment]
Like tycho said [here](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/98#issuecomment-1624988175), a credit account should be considered as TRUSTED. Before giving the credit limit, we would make sure the candidate doesn't have any supply balance. Issues related to assume credit accounts doing something strange are invalid. Giving the credit limit is a very critical thing. If the credit account really wants to hurt us, it could just not repay the debts. it doesn't even need to do things like this.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Sponsor comment.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/96/#issuecomment-1606054720): rejected
