### ISSUE TITLE
deadrxsezzz - calculateLiquidationOpportunity returns false results

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ironbank-judging#97]
deadrxsezzz

medium

# calculateLiquidationOpportunity returns false results

## Summary
`calculateLiquidationOpportunity` doesn't return correct values as it doesn't call `accrueInterest()` before calculating the liquidation opportunity. 

## Vulnerability Detail
When liquidating, interest is first accrued. 
```solidity
        _accrueInterest(marketBorrow, mBorrow);
        _accrueInterest(marketCollateral, mCollateral);
```
However, such thing isn't done in `calculateLiquidationOpportunity`
```solidity
function calculateLiquidationOpportunity(address marketBorrow, address marketCollateral, uint256 repayAmount)
        public
        view
        returns (uint256)
    {
        DataTypes.Market storage mCollateral = markets[marketCollateral];

        return _getLiquidationSeizeAmount(marketBorrow, marketCollateral, mCollateral, repayAmount);
    }
```
This would leave to wrong/ different results from the two.
Consider the following two scenarios:
1. Any project/ contract that is built on top of IronBank and first calls `calculateLiquidationOpportunity` and then `liquidate()` and verifies the two results will fail/ revert. 
2. If there is a market with low activity/ volume interest may not be accrued for a long time, a user might call `calculateLiquidationOpportunity` and based on the result decide to call liquidation. To his surprise, he may get different amount than the one expected. 

## Impact
Different results when liquidating than what was expected.

## Code Snippet
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L268-L276
https://github.com/sherlock-audit/2023-05-ironbank/blob/main/ib-v2/src/protocol/pool/IronBank.sol#L480-L510

## Tool used

Manual Review

## Recommendation
Accrue interest before calculating liquidation opportunity.

**Comment by iamjakethehuman** [comment]
Escalate for 10 USDC
I believe this to be a valid issue, would like to a see what the judge/ sponsor has to say

**Comment by 0xffff11** [comment]
Duplicate of https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/201

**Comment by hrishibhat** [comment]
Result:
Low
Unique considering this issue as low as this issue points to the incorrect value in a view function. Which is not used in the contracts.
